### ISSUE TITLE
autoproj2.0: autoproj does not generate the backup env.sh

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autoproj#102]
As mentiones in the email ```(env.sh-autoproj-v1)```

Maybe its related becasue the install stopps with a checkout error and therefor not created, however it makes it hard to switch back which is really annoing if you are willing to test new release (which are not working)

```git:https://github.com/orocos-toolchain/autoproj.git branch=master commit=74eb7a4929e509daa10d135d20e474de3fa3acf3 interactive=false push_to=git@github.com:/orocos-toolchain/autoproj.git repository_id=github:/orocos-toolchain/autoproj.git retry_count=10 tag=(/home/goldhoorn/dev-avalon-21/.autoproj/remotes/github__orocos_toolchain_autoproj_git): failed in import phase
```

**Comment by doudou** [comment]
I would really need the whole console output .... not just three lines that say really nothing.

**Comment by goldhoorn** [comment]
In which output you are interested?, the output from the install call?.
I not checked yet the given commit id, this might be a problem on my
install. But even the install of autoproj2.0 is failing it should not
replace the env.sh, or it should create the backup old-one before
starting...



On 17.11.2015 14:11, Sylvain Joyeux wrote:
>
> I would really need the whole console output .... not just three lines
> that say really nothing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/102#issuecomment-157366772>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
The complete console output. From the first command line to the point where you got the problem. Stop trying to limit the information to what you think is useful, because you're wrong more than 50% of the time (and then waste both my and your time)

And yes, it is a bug, I don't see how that's relevant. It's the actual reason why I ask for the console output.

**Comment by goldhoorn** [comment]
Please find the 'script' output attached:

[typescript.txt](https://github.com/rock-core/autoproj/files/36690/typescript.txt)

**Comment by doudou** [comment]
the backup env.sh is now saved before stage2 is started, which means before anything is done to the install itself.
