### ISSUE TITLE
autoproj 1.13.3: compute_normalized_layout: wrong number of arguments(3 for 0)

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#108]
I guess here is a typo and instead of normalized_layout it has to be compute_normalized_layout
https://github.com/rock-core/autoproj/blob/master/lib/autoproj/manifest.rb#L890

**Comment by doudou** [comment]
'master' is autoproj 2.x beta. Would you by any chance have sort of a mixed environment ?

**Comment by D-Alex** [comment]
Possible - we can close it and if I get the error again I can have a closure look.
