### ISSUE TITLE
autoproj tries to install autotools under Ubuntu 16.04

### ISSUE THREAD

**Issue by hemker** [rock-core/autoproj#122]
We found out that the following problem is rather a problem of autoproj's build-in default osdep sources:
https://github.com/rock-core/package_set/pull/103

**Comment by doudou** [comment]
As mentioned in rock-core/package_set#103, the built-in autotools is defined as autoconf/automake which does exist on 16.04. Could you by any chance having trouble with osdeps that you define somewhere else and would override autoproj's ?

**Comment by doudou** [comment]
Ping ?

**Comment by doudou** [comment]
https://github.com/rock-core/package_set/pull/103 and related bug fixed.
