### ISSUE TITLE
Autoproj 2 parallel update stuck when acessing the same git repo

### ISSUE THREAD

**Issue by planthaber** [rock-core/autoproj#123]
Hi, the mars simulation is organized by several packages all in the same repository (mars_package definition in package_set https://github.com/rock-simulation/simulation-package_set/blob/master/libs.autobuild ).

In autoproj 1 simply the first package checked out the git repository and the others each made an update. However with autoproj 2 and its parallel update, this leads to failures with the locking mechanism (see below).

Is there a way to tell autoproj 2 which packages should not be updated at the same time or which packages should not be updated in parallel?

```
simulation/mars/common/gui/config_map_gui(/data/jenkins/workspace/workspace/entern/Flavor/rock-15.05/node/Ubuntu_16.04/dev/simulation/mars/common/gui/config_map_gui): failed in import phase
    'git --git-dir /data/jenkins/workspace/workspace/entern/Flavor/rock-15.05/node/Ubuntu_16.04/dev/simulation/mars/.git config --replace-all remote.autobuild.fetch +refs/heads/*:refs/remotes/autobuild/*' returned status 255
    see /data/jenkins/workspace/workspace/entern/Flavor/rock-15.05/node/Ubuntu_16.04/dev/install/log/simulation/mars/common/gui/config_map_gui-import.log for details
    last 10 lines are:

      'USER'='jenkins'
      'VIZKIT_PLUGIN_RUBY_PATH'=''
      'WORKSPACE'='/data/jenkins/workspace/workspace/entern/Flavor/rock-15.05/node/Ubuntu_16.04'
      '_'='/data/jenkins/workspace/workspace/entern/Flavor/rock-15.05/node/Ubuntu_16.04/dev/.autoproj/bin/autoproj'
      'node'='Ubuntu_16.04'
    
    2017-01-12 07:57:24 +0000: running
        git --git-dir /data/jenkins/workspace/workspace/entern/Flavor/rock-15.05/node/Ubuntu_16.04/dev/simulation/mars/.git config --replace-all remote.autobuild.fetch +refs/heads/*:refs/remotes/autobuild/*
    in directory /data/jenkins/workspace/workspace/entern/Flavor/rock-15.05/node/Ubuntu_16.04/dev
    error: could not lock config file /data/jenkins/workspace/workspace/entern/Flavor/rock-15.05/node/Ubuntu_16.04/dev/simulation/mars/.git/config: File exists
Build step 'Execute shell' marked build as failure
```

**Comment by doudou** [comment]
The multiple-package-per-git scheme that mars is using has always been a hack, and I'm not sure I want to spend time supporting it in the future.

In the meantime, setting the 'interactive' flag on their importer should force autoproj to serialize the import of these packages.

```
mars:
   github: somewhere/mars
   interactive: true
```

**Comment by doudou** [comment]
Barring a constructive proposal related to this issue from your side, I'll make 2.0 the stable autoproj next week.

**Comment by planthaber** [comment]
Well, the "interactive: true" workaround is ok, also "autoproj update -p1" works by not allowing parallel updates at all.
