### ISSUE TITLE
gem install autoproj fails on Mac OS Sierra 

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#124]
I am getting the following error (gem version 2.0.14.1). Looks like a bug because of the weird dependency definition  >= 0.6.0, ~> 0.6.0. I guess it should be just >= 0.6.0 or just ~> 0.6.0.

manually  calling 'gem install autobuild' + 'gem install autoproj' solves the problem. 

    gem install autoproj
    ERROR:  While executing gem ... (Gem::DependencyError)
     Unable to resolve dependencies: autobuild requires pastel (>= 0.6.0, ~> 0.6.0); tty-prompt requires pastel (~> 0.6.0)

**Comment by doudou** [comment]
> manually calling 'gem install autobuild' + 'gem install autoproj' solves the problem.

So, as I understand it, running `gem install autoproj` fails, but running `gem install autobuild` first fixes the problem ?

Is that autoproj v1 ?

**Comment by D-Alex** [comment]
no this is autoproj v2

**Comment by doudou** [comment]
So ... why do you run 'gem` manually in the first place ?

**Comment by D-Alex** [comment]
Setting up a new installation by:
* manually coping init.rb manifest etc into a new autoproj folder
* calling autoproj envsh 
* calling autoproj update

**Comment by doudou** [comment]
The only supported way to install autoproj v2 without bootstrapping is through [the autoproj_install script](https://raw.githubusercontent.com/rock-core/autoproj/master/bin/autoproj_install) - which uses bundler. No exception.

How I understand it, the process for what you're doing:

```
ruby autoproj_install # possibly with --seed-config=/path/to/original/workspace/.autoproj/config.yml to retain configuration
cp -r /path/to/original/workspace/autoproj/ autoproj/
source env.sh
autoproj update
```
