### ISSUE TITLE
autoproj(2.02): deletes modified remotes

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#126]
if a package set is removed from the manifest autoproj deletes the remote even if it is locally modified

**Comment by doudou** [comment]
Yes. It has always been autoproj's behaviour. Given that it has always been there and that I don't have the time to deal with it, I'm not planning to fix that soon.

Leaving this issue open for future reference, though.

**Comment by doudou** [comment]
And duplicate of #16 

(Might get the "most hated autoproj bug" award ... feel free to fix it, though)
