### ISSUE TITLE
remotes/rock.core/overrides.rb complains about missing __dir__ method

### ISSUE THREAD

**Issue by HWiese1980** [rock-core/autoproj#129]
Hey collegues,

I'm just trying to install ROCK on my Ubuntu 16.04 PC via `bootstrap.sh`. Ruby is version 1.9.3 as recommended, installed via `rvm` (Ruby Version Manager). I leave all the configuration questions of the `bootstrap.sh` and `autoproj` at default values.

After asking me which CORBA implementation the RTT should use (which I also anwer with the default value `omniorb`, but for this issue it doesn't matter anyway what I answer there) I get the following error message: 

    overrides.rb(package_set=rock.core):32: undefined local variable or method `__dir__' for main:Object
      in /home/hwiese/Dokumente/ROCK/build/autoproj/remotes/rock.core/overrides.rb:32:in `<top (required)>'

This seems to be due to the fact that, according to different sources, Ruby 1.9.3 does not know the `__dir__` function. So how come it appears in the override.rb although Ruby 1.9.3 is the recommended version for ROCK?

Thanks and have a nice weekend!

**Comment by HWiese1980** [comment]
Seems only to be related to the `stable` bootstrap branch. It seems I can install ROCK using the Ubuntu system ruby 2.3.3 from the `master` branch. However I have to manually turn off `rock.simulation` in the `autoproj/manifest` because otherwise it complains about `simulation/orogen/mars` to be disabled...

`autoproj build` is running right now and I'm hoping for the things to come...

**Comment by doudou** [comment]
Indeed. __dir__ is a ruby 2.0+ keyword. 1.9.3 is only supported on the rock "releases". Moreover, you really should not be using 1.9.3 nowadays in any case except on legacy systems.

**Comment by HWiese1980** [comment]
I've figured that. However `stable` branch installation also fails on Ubuntu 16.04. It is said that there is a working commit for 16.04 and a new release tag would suffice. Since the desktops provided by our IT already have 16.04 preinstalled that would be great. 

I've managed to install Rock from the `master` branch but it is very clunky. There are a lot of header files that are renamed (like, capitalized), APIs don't work anymore and stuff like that. Though... that might be expectable from the master branch.

**Comment by doudou** [comment]
To be honest, Rock has an enormous problem w.r.t. releases (or, more accurately, the lack of them).

'stable' will not work on 16.04 without major cherry-picking. There has been some fundamental changes in 'master' since the last release, namely the removal of deprecated headers from base/types. To be fair, the last release and the last stable were already spitting out warnings about these deprecated headers.

**Comment by HWiese1980** [comment]
Oh dear... alright, so I'll go on and try to work with the parts of the master that I - as a complete Rock noob - feel able to fix without too much effort (like accordingly replacing #includes), ignore the rest and see how far I get. Thanks. Can you make use of effortlessly, blindly changed #includes (i.e. just replacing base/time.h with base/Time.hpp for instance) in the source tree? If you do, I'll see if I can help with providing the corresponding pull requests.

**Comment by doudou** [comment]
Wait a minute ...

Bootstrapping master from `github.com/rock-core/buildconf` should work just fine.

Which packages do you have, that still use the old includes ?

**Comment by HWiese1980** [comment]
Sorry, I can't look into it right now because I'm not in the office anymore and also won't be until Monday next week. I'll get back to you then. I think, and this comes from the very back of my head, one of the packeges was `drivers/qualisys`. But don't nail me down to it.
