### ISSUE TITLE
Autoproj bootstrap fails if ruby-dev is not installed

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/autoproj#132]
Happens on Ubuntu 16.04. 

starting the newly installed autoproj for stage2 install
saving env.sh and .autoproj/env.sh
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

/home/scotch/Arbeit/entern/autoproj/init.rb:26: mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
failed to run autoproj envsh on the newly installed autoproj (/home/scotch/Arbeit/entern/.autoproj/bin/autoproj)
autoproj_bootstrap:570:in `call_stage2': failed to execute autoproj install-stage2 (RuntimeError)
        from autoproj_bootstrap:601:in `<main>'

Installing ruby-dev fixes this issue. Is it possible to autoinstall the package
prior to stage 2 ?

**Comment by doudou** [comment]
> /home/scotch/Arbeit/entern/autoproj/init.rb:26

Given where the error is, it does not look like a problem with autoproj but one with your init.rb.

**Comment by jmachowinski** [comment]
I agree might be an issue in the init.rb
line 26 is an require 'mkmf'
anyway, it is hard to test now, as I just installed my system...
Closing as invalid
