### ISSUE TITLE
amake test . results in unexpected behaviour

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/autoproj#136]
The result of amake test .  was that it tried to build
ndlcom/ndlcom_device_driver_test.
I found this rather unexpected. Bug or feature ?

**Comment by doudou** [comment]
What were you expecting `amake test` to do ?

`amake` is `autoproj build`, so, unless you have a test/ folder in which there are packages`amake test` builds every package that has `test` in it

**Comment by jmachowinski** [comment]
unexpected was that is just started building anything 
that contained 'test', instead of accepting a full package 
name only.

**Comment by doudou** [comment]
All autoproj commands behave like that. If you give a full package path or name, it will use that. Otherwise, it's trying to do partial matches.
