### ISSUE TITLE
Usage of autoproj clean unclear

### ISSUE THREAD

**Issue by 2maz** [rock-core/autoproj#139]
$workspace/test_bootstrap_v2# autoproj clean
  this is going to clean all packages. Is that really what you want ? [false] true

no packages or OS packages match 

It looks like autoproj clean requires a  list of packages as arguments, but that is not clear from the --help command.

**Comment by doudou** [comment]
Bug, it should pass. The question happens *because* you've not provided any package

**Comment by doudou** [comment]
Should be fixed by v2.1.0
