### ISSUE TITLE
autoproj v2: explicit autoproj osdeps vs. implicity run within aup

### ISSUE THREAD

**Issue by 2maz** [rock-core/autoproj#143]
In #140 is has been mentioned that autoproj osdeps is run implicitly with aup. 
So I would expect that after running aup (multiple times actually) that 'autoproj osdeps' would have nothing more to do. Yet, in my case only a dedicated call to 'autoproj osdeps' installed all os dependencies.

To help narrowing the issue: in that particular case these were osdeps introduced by overriding existing package definitions, e.g., to replace base/cmake with the debian package for base/cmake (for example: https://github.com/2maz/rock-osdeps/blob/master/data/master-17.06-amd64.yml)

**Comment by doudou** [comment]
To debug, the result of the source/osdep resolution and partition happens here: https://github.com/rock-core/autoproj/blob/master/lib/autoproj/cli/update.rb#L109

The osdep packages at this point are package names, not resolved osdeps. The installation happens a little bit later in the same method.

**Comment by 2maz** [comment]
Ok, checked: user's (my) fault. This only happens when aup fails with warnings, thus never getting to the osdep stage.  Looks better with `aup -k`. Sorry for the noise.
