### ISSUE TITLE
Version control definition in build configuration

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#146]
For very small projects it would be convenient to have autoproj read version control and package definitions (source.yml, *.osdeps and *.autobuild) from the build configuration without the need for external package sets

**Comment by doudou** [comment]
It does.

The only oddity is that in `autoproj/` the source.yml is actually called `overrides.yml`. `*.autobuild` and `*.osdeps` are read as-is.

**Comment by g-arjones** [comment]
👍 

Awesome. Should have tried that... Thanks!
