### ISSUE TITLE
autoproj 2.03: git submodule not reseted to correct commit id

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#147]
If autoporj is used in combination with git submodules and tags the submodule is not properly updated to the correct commit id after the main git was rested to the given tag after checkout. 

Workaround:
call: 'git submodule update' after checkout to sync submodule

**Comment by doudou** [comment]
Actually, it seems that submodules are only handled at checkout time.

Is running "git submodule update" after an update of the "master" repo the right workflow in all cases ?

**Comment by jakobs** [comment]
Maybe 'git submodule update --init' to catch the cases where new submodules have been added?

**Comment by doudou** [comment]
I'll add a test ... I really know nothing about submodules. They're a pain.

**Comment by doudou** [comment]
https://github.com/rock-core/autobuild/pull/37
