### ISSUE TITLE
auto-adding trash folder

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-core/autoproj#148]
Autoproj auto-added one of my trash folders:

```
  auto-adding /home/dfki.uni-bremen.de/afabisch/.local/share/Trash/files/visualizer using the cmake package handler
  ...
  configured CMake for ../../.local/share/Trash/files/visualizer         
  built ../../.local/share/Trash/files/visualizer                  
  installed ../../.local/share/Trash/files/visualizer
```

The reason is that I was in the folder when I called amake, because I deleted the original folder previously from nautilus and the bash seems to switch automatically to the trash folder. Is this an intended behavior?

**Comment by doudou** [comment]
It is intended. Amake is `autoproj build .`, so you explicitely asked autoproj to build this.

Bash does not switch automatically. Nautilus moves the folder, so bash just "ends up" being in the trash folder. It would be the same if you moved the folder somewhere else.
