### ISSUE TITLE
amake got stuck

### ISSUE THREAD

**Issue by hemker** [rock-core/autoproj#149]
Hey,
since the beginning of the week, some users experience that amake got stuck and does not go further than "typelib: using the castxml importer" and some following "WARN: ... from ... does not have a manifest". Doing a new bootstrap succeeds, but then an "amake <PACKAGE>" does not do anything; one cpu core is used at 100 percent. Autoproj version is the latest for every concerned user and the Ubuntu systems are up-to-date.
Also running amake with ruby -rdebug or autoproj with verbose option did not result in any usable outcome.

Best,
Dennis

**Comment by chhtz** [comment]
This issue appears to be resolved (or worked around) by this: https://github.com/rock-core/autobuild/commit/bb36226e1e96b7629ed39aa362bb44ac73d5c087
