### ISSUE TITLE
avoid having to reload the whole config in `which` and `exec`

### ISSUE THREAD

**Issue by doudou** [rock-core/autoproj#164]
The idea here would be to cache the environment as generated *plus* the data needed to validate this environment.

Implementation-wise, we would need to store a list of files with size, timestamp and SHA that would allow us to validate whether the current cache is valid. The files that can change the environment are:
- all the gemfiles
- all the .rb files
- all the .autobuild files
- all the manifest.xml
- .autoproj/config.yml
- the main manifest (autoproj/manifest)=

I think these same files are the dependencies of `installation-manifest`, so that would allow us to watch for changes there. In addition, we will have to provide a public API to allow a package set to register additional files if needed.

Then, we have two codepaths in `which` and `exec`: get PATH from a cache file if the dependencies validate, load the whole config otherwise. Just like with `locate`, we can reduce the amount of files required in the codepath to a minimum, this allowing a quicker execution.

In addition, we can then easily implement a `autoproj envsh --watch` that would be extremely useful for e.g. vscode (https://github.com/rock-core/vscode-rock/pull/28/files).

**Comment by g-arjones** [comment]
Sounds good..  Specially `--watch`
