### ISSUE TITLE
the "ignoring ROS manifest" ... message is annoying on a standard Rock install

### ISSUE THREAD

**Issue by doudou** [rock-core/autoproj#186]
The orocos-toolchain packages have a `package.xml`, and therefore it triggers multiple times on every Rock install.

Not sure whether it would make sense to just remove the warning ... @g-arjones ?

**Comment by g-arjones** [comment]
I think the warning makes sense but I would not have a problem with removing it. Maybe add an option to supress this warning (not sure how though)?

**Comment by doudou** [comment]
> Maybe add an option to supress this warning (not sure how though)?

Not sure how either ... I'll remove it for now. If we start seeing a problem with the lack of warning, we can dig further. This shouldn't happen really often, does it ?

**Comment by g-arjones** [comment]
> This shouldn't happen really often, does it ?

I don't think so.

> I'll remove it for now.

No problem.. Go ahead :+1:
