### ISSUE TITLE
Disable git protocol for host

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/autoproj#19]
Hey, 
we got a new git server, which does not support the git protocol.
As far as I can see, there is no option, to disable the git protocol
in gitorious_server_configuration. Only workaround I would see
for now is to set the git_url to "git@#{base_url}". 
By the way, gitorious_server_configuration is a horrible name. 
Should be git_server_configuration.
Greetings
   Janosch

**Comment by doudou** [comment]
In both autoproj 1.12.6 and 1.13.0 beta, call gitorious_server_configuration with the following options:

```
default: 'http,ssh', disabled_methods: 'git' option.
```
