### ISSUE TITLE
auto-add mechanism should work for dependencies

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#207]
Consider the following scenario:

1. Packages 'foo' and 'bar' exist in the source tree but not in any package set nor it is in the layout section of the manifest;
2. Package 'foo' depend on 'bar';
3. Package 'foo' is explicitly selected for build in the command line (`amake foo`).

The operation will fail because 'bar' won't be resolved. Autoproj should look for 'bar' in the workspace and auto-add it if possible.

**Comment by doudou** [comment]
> Autoproj should look for 'bar' in the workspace and auto-add it if possible.

This goes into the "too much magic" for my taste. Auto-add is meant as a on-off feature, not a main workflow. One can add packages manually to the manifest to force auto-adding them without having to put them on the command line, which is IMO a good in-between.

**Comment by g-arjones** [comment]
I personally think that it would be useful to be able to quickly clone and use a few packages in the workspace without having to touch the configuration just for testing purposes. Adding them to the manifest is not too painful though, so let's leave it as it is..
