### ISSUE TITLE
provide shell completions scripts

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#208]
The idea is to provide completion scripts for (at least) bash, fish and zsh. To achieve this multi-shell support, two designs are possible:

1. Create a workspace config option to allow the user to choose what shell he/she wants to use;
2. Generate env scripts (env.sh, env.bash, env.fish, env.zsh) for each one of the supported shells.

If we decide to go for (1), there are a couple of choices to make:

a. Which one will be the default;
b. Will the generated script be named env.sh regardless of the selected shell? Changing the script name kinda breaks backwards compatibility with external tools though.

Personally, I think I prefer (2). @doudou thoughts?

**Comment by doudou** [comment]
I definitely prefer (1)

**Comment by doudou** [comment]
OK ... not a lot of rationale :P:

The only time where (2) (or changing the env.sh file name in (1)) would make sense is if a given installation is meant to be used by more than one person (which leads to: more than one shell). I don't see that as a major driver.

**Comment by g-arjones** [comment]
Hm.. Interestingly enough, you merged (1) 8 days ago :P

**Comment by doudou** [comment]
> Hm.. Interestingly enough, you merged (1) 8 days ago :P

I know. I missed the issue back then. So, I'm consistent, I like (1) and I merged (1) :P
