### ISSUE TITLE
create an API/machanism to allow packages to provide env/completion scripts

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#209]
The easy/lazy/obvious way is to automatically copy the scripts from a given folder in the source packages to some folder in the installation prefix (Autoproj.prefix/share/autoproj/env.d ?) and source these files from the generated env.sh.

**Comment by doudou** [comment]
For env files, I'm actually 100% against, as it will break things like `autoproj exec`.

For completion scripts, well, why not sticking with the source_after/source_before ?

**Comment by g-arjones** [comment]
Yeah, forgot we had that discussion already. source_after/source_before relies on the package set explictly loading the the scripts. But that's just my use case, I guess... feel free to close
