### ISSUE TITLE
bundler gem not found on bootstrap

### ISSUE THREAD

**Issue by vbargsten** [rock-core/autoproj#217]
On new install got the message "gem install bundler returned successfully, but still cannot find bundler". Originating from here:
https://github.com/rock-core/autoproj/blob/4ae9a7c3fb908da7bdf2639d0c3915119a60ab97/bin/autoproj_bootstrap#L295

Investigation shows gem which returns system's bundler
```
$ GEM_HOME="/home/vbargsten/.autoproj/gems/ruby/2.5.0" GEM_PATH="/home/vbargsten/.autoproj/gems/ruby/2.5.0" gem which bundler
/usr/lib/ruby/vendor_ruby/bundler.rb
```

Calling with `-a` to give all results:

```
$ GEM_HOME="/home/vbargsten/.autoproj/gems/ruby/2.5.0" GEM_PATH="/home/vbargsten/.autoproj/gems/ruby/2.5.0" gem which -a bundler
/usr/lib/ruby/vendor_ruby/bundler.rb                                                                                                                                                         
/home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/bundler-1.16.4/lib/bundler.rb
```

A quick fix for me was to call with `-g`:
```
$ GEM_HOME="/home/vbargsten/.autoproj/gems/ruby/2.5.0" GEM_PATH="/home/vbargsten/.autoproj/gems/ruby/2.5.0" gem which -g bundler                            
/home/vbargsten/.autoproj/gems/ruby/2.5.0/gems/bundler-1.16.4/lib/bundler.rb
```

System is Ubuntu 18.04

**Comment by AlexanderFabisch** [comment]
I have the same problem on Ubuntu 16.04 in a docker container. I try to run something like this:

```
AUTOPROJ_BOOTSTRAP_IGNORE_NONEMPTY_DIR=1 ruby autoproj_bootstrap git $GITURL branch=$BRANCH
```

I get the following error message:

```
Detected 'gem' to be /usr/bin/gem2.3
ERROR:  Can't find ruby library file or shared library bundler/setup
Installing bundler in /tmp/infuse/.autoproj/config.yml/ruby/2.3.0
Fetching: bundler-1.16.4.gem (100%)
ERROR:  While executing gem ... (Errno::EEXIST)
    File exists @ dir_s_mkdir - /tmp/infuse/.autoproj/config.yml
FATAL: failed to install bundler in /tmp/infuse/.autoproj/config.yml/ruby/2.3.0
ERROR:  Can't find ruby library file or shared library bundler/setup
gem install bundler returned successfully, but still cannot find bundler in /tmp/infuse/.autoproj/config.yml/ruby/2.3.0
```

Hotfix for me was

```
mkdir .autoproj
```

and everything runs fine.

**Comment by g-arjones** [comment]
@AlexanderFabisch  doesn't seem like these are the same issues to me. Particularly, from your logs, this is weird:

```
Installing bundler in /tmp/infuse/.autoproj/config.yml/ruby/2.3.0
```

How come autoproj trying to create a DIRECTORY named `config.yml` to install the gems (this is supposed to be a configuration file). You mentioned you are running in a docker container, maybe you are missing a proper environment setup?

**Comment by AlexanderFabisch** [comment]
OK, yes, seems to be unrelated but fails with the same error message.

**Comment by AlexanderFabisch** [comment]
Opened #218

**Comment by doudou** [comment]
@vbargsten seem to be triggered by the presence of the bundler Ubuntu package ... I'll try to investigate. Unfortunately, I'll be travelling in the next days.
