### ISSUE TITLE
How to use autoproj non-interactively in a Docker image

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-core/autoproj#218]
I have a docker image that uses autoproj. The Dockerfile looks like the following:

```docker
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y ...
RUN pip3 install --upgrade pip
RUN pip3 install ...

RUN mkdir -p -m 700 /root/.ssh/ && echo some.server.com >> /root/.ssh/known_hosts

# Prepare non-interactive autoproj setup with CI user
WORKDIR /tmp/infuse
COPY config.yml /tmp/infuse/.autoproj/
RUN wget http://www.rock-robotics.org/autoproj_bootstrap --directory-prefix=/tmp/infuse/
RUN AUTOPROJ_BOOTSTRAP_IGNORE_NONEMPTY_DIR=1 ruby autoproj_bootstrap git GITURL branch=BRANCH
COPY 00_ci_user.yml /tmp/infuse/autoproj/overrides.d/
COPY manifest /tmp/infuse/autoproj/

# Autoproj needs these to be defined (will be removed later):
RUN git config --global user.email infuse@example.com \
  && git config --global user.name InFuse

SHELL ["/bin/bash", "-c"]

RUN source env.sh && autoproj update
...
```

Everything went fine in a previous version. With some updates I have the following problem during bootstrap:

```
AUTOPROJ_BOOTSTRAP_IGNORE_NONEMPTY_DIR=1 ruby autoproj_bootstrap git GITURL
Detected 'gem' to be /usr/bin/gem2.3
ERROR:  Can't find ruby library file or shared library bundler/setup
Installing bundler in /tmp/infuse/.autoproj/config.yml/ruby/2.3.0
Fetching: bundler-1.16.4.gem (100%)
ERROR:  While executing gem ... (Errno::EEXIST)
    File exists @ dir_s_mkdir - /tmp/infuse/.autoproj/config.yml
FATAL: failed to install bundler in /tmp/infuse/.autoproj/config.yml/ruby/2.3.0
ERROR:  Can't find ruby library file or shared library bundler/setup
gem install bundler returned successfully, but still cannot find bundler in /tmp/infuse/.autoproj/config.yml/ruby/2.3.0
```

**Comment by AlexanderFabisch** [comment]
@g-arjones Opened a new ticket for this. Do you have an idea why config.yml is interpreted as a directory? That seems to make non-interactive installation with autoproj nearly impossible.

**Comment by AlexanderFabisch** [comment]
Is there a way to switch to an old version of autoproj?

**Comment by g-arjones** [comment]
I can't reproduce this on my end.. Could you please put together a Dockerfile that I can actually use?

> Is there a way to switch to an old version of autoproj?

Yes, create a Gemfile with the pinned version and pass it to `autoproj_bootstrap` script with `--gemfile=PATH_TO_GEMFILE`

**Comment by AlexanderFabisch** [comment]
OK, sorry for the trouble. @vbargsten helped me to find the error. My initial config.yml contained

```
gems_install_path: "/tmp/infuse/.autoproj/config.yml"
```

which seems to make no problems in previous versions of autoproj. I set it to `/root/.autoproj/gems` now. Also the more autoproj-like way of setting an initial configuration file is probably `autoproj_bootstrap --seed-config=FILENAME`.
