### ISSUE TITLE
autoproj show seems to checkout missing packages behind the scenes

### ISSUE THREAD

**Issue by doudou** [rock-core/autoproj#224]
The CLI seems to be blocking without reason. Moreover, intuitively I am assuming that `show` is non-modifying.

**Comment by g-arjones** [comment]
Steps to reproduce?

**Comment by doudou** [comment]
> Steps to reproduce?

Actually, trying to reproduce, I don't manage.

So, it seemed to be something else .... which I should have checked before I came here and opened an issue. Sorry for the noise !
