### ISSUE TITLE
Multiple definitions of the same package seem to favour the less specific package_sets

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#231]
When defining a package PKG in package set A, and also in B, and when B imports A, it seems that the definition of A is favoured over the definition of B.

It says in the log:
WARN: PKG from B is overridden by the definition in A

Source is:
https://github.com/rock-core/autoproj/blob/c2871de201c2236697d8422f24e10933da7165be/lib/autoproj/autobuild_extensions/dsl.rb#L154

My intuition is that the second definition of PKG should override the first one, not vice versa. Rational being that packages defined in mainly source packages like rock.core should be overridable in project specific package sets.

**Comment by doudou** [comment]
Very subjective IMO

I'd like to note that this has been the behavior of autoproj from day 1, and I still have to encounter a use-case for it. The one thing you can't override in downstream packages is the package type, and I kind (e.g. move from cmake to autoconf) of feel like this is a very cornery-case.

Moreover, and maybe more importantly, it's hard to implement
