### ISSUE TITLE
bundler fails during aup of clean rock-bootstrap

### ISSUE THREAD

**Issue by dettmann** [rock-core/autoproj#232]
Hi,

in a clean bootstrap (just rock-core) aup crashes after updating the package-sets and packages with (ubuntu16.04):

 bundler: connected to https://rubygems.org/
/usr/lib/ruby/vendor_ruby/bundler/lockfile_parser.rb:72:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
	from /usr/lib/ruby/vendor_ruby/bundler/lockfile_parser.rb:59:in `initialize'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:61:in `new'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:61:in `initialize'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:173:in `new'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:173:in `to_definition'
	from /usr/lib/ruby/vendor_ruby/bundler/dsl.rb:11:in `evaluate'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:24:in `build'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:120:in `definition'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:88:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler/setup.rb:18:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  WARN: saved the new Gemfile in /media/Daten/GITs/FLEXIPICK/install/gems/Gemfile.FAILED and restored the last Gemfile version
/home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/package_managers/bundler_manager.rb:360:in `install': bundler executed successfully, but the result was not in a clean state (Autoproj::PackageManagers::BundlerManager::NotCleanState)
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/os_package_installer.rb:410:in `install_manager_packages'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/os_package_installer.rb:400:in `block in install'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/os_package_installer.rb:399:in `each'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/os_package_installer.rb:399:in `install'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/workspace.rb:775:in `install_os_packages'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/cli/update.rb:127:in `run'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/cli/main.rb:104:in `block in run_autoproj_cli'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/reporter.rb:95:in `block in report'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autobuild-1.16.0/lib/autobuild/reporting.rb:88:in `report'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/reporter.rb:92:in `report'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/cli/main.rb:94:in `run_autoproj_cli'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/lib/autoproj/cli/main.rb:212:in `update'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /home/dfki.uni-bremen.de/dettmann/.autoproj/gems/ruby/2.3.0/gems/autoproj-2.8.8/bin/aup:17:in `<top (required)>'
	from /media/Daten/GITs/FLEXIPICK/.autoproj/bin/aup:45:in `load'
	from /media/Daten/GITs/FLEXIPICK/.autoproj/bin/aup:45:in `<main>'

**Comment by doudou** [comment]
It looks like there's a mixup between Bundler 1.x and bundler 2.x. It seems that the `ruby-bundler` APT package has been installed. Could you try again after uninstalling it ?

**Comment by 2maz** [comment]
Just checked, its a mixup. With ruby-bundler installed in the system the error is triggered, without it is working fine.

**Comment by doudou** [comment]
I'm firing up a VM .... I'll check why it picks one bundler one time and the other the other time

**Comment by doudou** [comment]
Could you guys give #234 a try ?

See https://github.com/rock-core/autoproj#developing-autoproj-2x for instructions on how to use a local checkout.

**Comment by 2maz** [comment]
Fix works only after adapting the regexp. See comments on #234
