### ISSUE TITLE
Autoproj does not respect build order when install step is disabled

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#266]
Script to reproduce:

```bash
#!/bin/bash

[[ -f "autoproj_install" ]] || \
    wget -nv https://github.com/rock-core/autoproj/raw/master/bin/autoproj_install

ruby autoproj_install --no-interactive
mkdir -p autoproj

cat <<EOF > autoproj/manifest
layout:
  - one
EOF

cat <<EOF > autoproj/overrides.yml
version_control:
  - one:
    type: git
    url: git@github.com:enki/libev.git
  - two:
    type: git
    url: git@github.com:enki/libev.git
EOF

cat <<EOF > autoproj/packages.autobuild
['one', 'two'].each do |name|
    autotools_package(name) do |pkg|
        pkg.use autogen: false
        def pkg.install; end
    end
end

setup_package('one') do |pkg|
    pkg.depends_on 'two'
    def pkg.build
        two = Autoproj.workspace.manifest.find_autobuild_package('two')
        raise Autoproj::ConfigError, "Package 'two' should be built at this"\
                                     " point, but it is not" unless two.built?
        super
    end
end
EOF

source env.sh
aup --no-interactive
amake --no-interactive
```

**Comment by doudou** [comment]
I'm actually puzzled that the package whose install step is disabled builds at all. 'build' is not a step in autobuild, 'install' is the only step. Disabling it basically breaks the dependency chain.

If you want to avoid installing, but still want to build, then just reimplement 'install' on this package.

~~~
def pkg.install
end
~~~

**Comment by g-arjones** [comment]
Still fails

**Comment by g-arjones** [comment]
I have updated the test script above

**Comment by doudou** [comment]
one other thing .. As far as I remember, built? is set if the package has actually been built. If it does not need to be built during the run (i.e. was not modified), it won't be set. A better test would be to display something in both packages' build method.

**Comment by g-arjones** [comment]
Actually, reimplementing `#install` rather than disabling the install phase fixes my original issue (broken dependency chain). The reason the suggested test was still failling was because `@built` is set in the base `Autobuild::Package` class, which as you quickly pointed out, only knows about 'install' (which is kinda weird)

**Comment by doudou** [comment]
> (which is kinda weird)

Very. Indeed :(
