### ISSUE TITLE
autoproj is enabling tests for packages that do not have a test folder

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#274]
This is a regression from #270

**Comment by g-arjones** [comment]
Actually, this is an api breaking change.. Setting `test_utility.source_dir` in overrides.rb now enables tests regardless of the presence of the `test` folder

**Comment by g-arjones** [comment]
Something also worth noting: doc_utility and test_utility now have different behaviour regarding task creation and installation of dependencies during first checkout

**Comment by g-arjones** [comment]
Also, It's not possible to use `pkg.with_tests { ... }` to set a custom test task in the post import hook because the package handler sets one first

**Comment by g-arjones** [comment]
Setting up the test utility in post import hooks delays enablement of the utility which, in turn, prevents test_dependencies from being selected by the CLI (on current released version of autoproj)

**Comment by doudou** [comment]
> Actually, this is an api breaking change.. Setting test_utility.source_dir in overrides.rb now enables tests regardless of the presence of the test folder

Setting `source_dir` is meant to enable tests. It is its very purpose, actually: setting `source_dir` declares that the tests are available.

> Also, It's not possible to use pkg.with_tests { ... } to set a custom test task in the post import hook because the package handler sets one first

... which was even worse before (not arguing whether it's a good and bad thing, just that before the test task was defined even earlier than post_import)

> Setting up the test utility in post import hooks delays enablement of the utility which, in turn, prevents test_dependencies from being selected by the CLI (on current released version of autoproj)

Not sure how this is relevant. The DSL change that moved the utility setup to post_import is part of autoproj itself. So how "the current released version of autoproj" is relevant here ?

I'm sure you are on to something, but very confused by your description. Could you create some reproducing test cases ?

**Comment by g-arjones** [comment]
> Setting source_dir is meant to enable tests. It is its very purpose, actually: setting source_dir declares that the tests are available.

It wasn't like that before.. I was setting `source_dir` as part of the package setup in my custom handlers.  Wanted to give a heads up because wasn't sure if that was intentional or not.

> ... which was even worse before (not arguing whether it's a good and bad thing, just that before the test task was defined even earlier than post_import)

Before, it was possible to guarantee I was calling `with_tests` in a custom package handler by simply calling it before calling the common handler. Now, one has to assume that the hooks will be called in the order that they were added. Kind of makes sense buts feels more fragile, IMO..

> Not sure how this is relevant. The DSL change that moved the utility setup to post_import is part of autoproj itself. So how "the current released version of autoproj" is relevant here ?

Just because you updated the package sets already...

> I'm sure you are on to something, but very confused by your description. Could you create some reproducing test cases ?

I thought it was a bug at first and then realized it was just an API breaking change (the `source_dir` thing). Kept it open because I wasn't sure if you meant to do that or not

**Comment by doudou** [comment]
> It wasn't like that before.. I was setting `source_dir` as part of the package setup in my custom handlers. Wanted to give a heads up because wasn't sure if that was intentional or not.

Not intentional. But my understanding of the code is that the change makes setting `source_dir` in the autobuild files more deterministic. Before, you would have a different behavior if setting it up before the common setup (would enable) or after (would not enable).

> Now, one has to assume that the hooks will be called in the order that they were added.

You can still call `with_tests` within the package setup, which is guaranteed to be before the `post_import` blocks. Can't you ?

> Just because you updated the package sets already...

The rock.core package set change is only involved with reading the `enabled?` flags. It's not involved in configuring anything. So, I don't see where is the interaction.

**Comment by g-arjones** [comment]
All true.. The point is moot then. Feel free to close.
