### ISSUE TITLE
 `undefined method `member?'` Error with empty layout

### ISSUE THREAD

**Issue by ivan1993br** [rock-core/autoproj#315]
**Environment**
Currently I have a manifest where I concentrate package sets for different projects, it is basically used for CI tests, it has no package on layout.

On this manifest I have no interest to add any packages to be update, is just a package list assembly. If I need one, I specify it.

**Problem**
After this [PR](https://github.com/rock-core/autoproj/pull/314), the empty layout causes a crash, because the `data["layout"]` will not exit and has no `member?` function, as I have no package to update, just the package sets.

**Point of View**
I think that my empty package set is coherent, and should be possible. Although a manifest is mainly used for a build configuration for my workspace, implying that I would need something to build. I do not see a problem to allow empty manifest, for particular cases like this one.

**Solution 1 with current modification with @g-arjones  advice**
I can insert a empty `- ` package on the manifest. I do not like this idea because I think that there is no problem allowing no layouts (which I was doing until now), and the warning makes no sense for my case, I mean, the warning is coherent, but what I want is no package at all.

**Solution 2 another PR**
Check for the existence of the layout before checking the empty entry.

Finally, I will be more then happy to do this new PR if you guys agree with my thoughts. So, what do you think?

**Comment by doudou** [comment]
> Finally, I will be more then happy to do this new PR if you guys agree with my thoughts. So, what do you think?

I agree with your point of view (this was expected behavior, actually). Please do the PR.
