### ISSUE TITLE
Check installed packages with pip package manager

### ISSUE THREAD

**Issue by ivan1993br** [rock-core/autoproj#319]
Nowadays Autoproj does not check if a PIP package is installed or not, like dpkg apt. (And depending on how many pip packages you have this take some time, and is always executed)

What do you guys think about adding this functionality to the pip?

One concern that I have with this update is that today, Autoproj does not have a `version manager` for the packages, so when I want to install a specific version of a pip package I add on the osdeps:

```yaml
pip:
   - my-package==0.0 (If I want the 0.0 version)
```
My proposal is that we use `pip show` to parse [like here with dpkg](https://github.com/rock-core/autoproj/blob/04d1cc4fd819620e5e26d3cfda7c6b20e21f52f5/lib/autoproj/package_managers/apt_dpkg_manager.rb#L39)  checking the existance and version of the package, and if does not exist, or the version is lower than the specified, execute the pip install command, [like here with the dpkg](https://github.com/rock-core/autoproj/blob/04d1cc4fd819620e5e26d3cfda7c6b20e21f52f5/lib/autoproj/package_managers/apt_dpkg_manager.rb#L117).

**Comment by g-arjones** [comment]
How would you know that there's a more recent version of the module? As far as I know, `pip show` will only tell what version you have installed, not the version that is available.

If I understood what you are proposing, to update a pip package I would have to explicitly change its osdeps entry, right?

**Comment by ivan1993br** [comment]
>How would you know that there's a more recent version of the module? As far as I know, pip show will only tell what version you have installed, not the version that is available.

yes, but what I thought is that, if the version you require is higher than the one existent you try to install, if it doesn't exist, it fails. Today it tries to install anyway, and it fails if does not exist. 

> If I understood what you are proposing, to update a pip package I would have to explicitly change its osdeps entry, right?

I see the problem with what I was proposing, with guaranteeing that we have the last updated package, with a non version specified pip package (my bad). What about: if the osdeps has `my_pakcage==0.0`, we if check the correct version is higher than the one present, if not, update, if yes, pass and do nothing. And if we have just `pip: my_package` we proceed with the normal installation.

**Comment by g-arjones** [comment]
What if I say

```yml
pip:
   - my-package>=1.0
```

AFAIK, pip even allows something like `my-package>=1.0,<=1.9`.

I think what you want ultimately can be implemented but doesn't sound that trivial to me. Autoproj in fact has no knowledge of package versions (it simply forwards the package name string to `pip install`) so that would have to be implemented if you want true version management.

@doudou Thoughts?

**Comment by ivan1993br** [comment]
>I think what you want ultimately can be implemented but doesn't sound that trivial to me

Yes, I saw how far I was after your last comment... This was an idea that I had for a specific problem of mine. And the time that the pip update annoys me sometimes, specially in a poor connection, and when I know there is nothing to be updated.

What do you think to run a `pip list -o --user` on the begin of update and see the current and last available version of a package? With this, it would not be exactly a version manager, more a "update check?", I mean, if you set a package, we check what we can (with no version specified, see if is the latest one with `pip list`, if is `==`, check if is the one installed, if is `>=` check if there is one compatible available.) The other cases I agree that we would need a true version management, or something closer to achieve (which I am on board with this idea, but like you said, it would not be simple)

Maybe this solution solution lacks too much consistency? I mean, we would only partially check version for pip... However, I don't think it would break any backwards compatibility, and would cover most cases.

**Comment by doudou** [comment]
> Maybe this solution solution lacks too much consistency? I mean, we would only partially check version for pip... However, I don't think it would break any backwards compatibility, and would cover most cases.

I think @g-arjones message is that it will have to be implemented in Autoproj's pip handler. Feel free to propose a pull request in that direction, I personally don't see a problem having the functionality.

**Comment by ivan1993br** [comment]
I will close this issue, I think that a version manager just on PIP is not a good way to go. But I will be happy to help if needed on a version management implementation in a future Autoproj release.
Thanks!
