### ISSUE TITLE
`pip` is not available on newer linux distros (as ububunto focal fossa)

### ISSUE THREAD

**Issue by ivan1993br** [rock-core/autoproj#320]
## Problem

We do not have `python pip` dependency on ubuntu newer release, neither `pip`. Just `python3-pip` and `pip3` respectively. This does prevent the user to define python packages( with pip manager).

## Discussion

The dependency problem we may use `osdeps` to solve, however the `pip` call, I think it is trickier. 
Another way is create a new package `pip3` and add pip3 definition.

What do you guys think about it?

**Comment by planthaber** [comment]
Python 2 reached its end of life on January 1st 2020 (no further support, bug- or security fixes), so moving to python3 should be the way to go. As far as I remember the only reason python2 is available in ubuntu is that they were not finished removing or porting python2 packages.

But nevertheless, with Thomas new python integration, autoproj should pick the python (and pip) version you select (python3 is the default), but when you select python2 in that stage, pip2 should be called. 

I think you should not mix python versions in a single workspace. This will backfire when you start using those pip packages in you own python packages.

**Comment by ivan1993br** [comment]
> But nevertheless, with Thomas new python integration, autoproj should pick the python (and pip) version you select (python3 is the default), but when you select python2 in that stage, pip2 should be called.

Curiosty, what is the "Thomas new python integration"?

>I think you should not mix python versions in a single workspace. This will backfire when you start using those pip packages in you own python packages.

I agree, what I would like is not have to define `pip` and `pip3` for the same base python packages. Unfortunately there is some projects that still uses python 2, and I would like to keep the same package sets for both, for the base python packages.

**Comment by 2maz** [comment]
> Curiosty, what is the "Thomas new python integration"?

I added some python integration in the rock-core package set, see https://github.com/rock-core/package_set/blob/master/rock/python.rb. Users are asked to select the python version to use, so that python and pip shims are set accordingly for your workspace.

**Comment by ivan1993br** [comment]
>I added some python integration in the rock-core package set, see https://github.com/rock-core/package_set/blob/master/rock/python.rb. Users are asked to select the python version to use, so that python and pip shims are set accordingly for your workspace.

I did not know about them, very nice! However, I would like to use Autoproj with `pip` packages without adding ROCK stuff. What about porting these modifications to the Autoproj itself?

**Comment by planthaber** [comment]
We discussed starting a python only package_set a bit in here: https://github.com/rock-core/rock-package_set/pull/234

So this is a valid option for us, but we did not have time until now to do it.

**Comment by doudou** [comment]
Tbh, I think it would make more sense to add it to autoproj itself

**Comment by ivan1993br** [comment]
> Tbh, I think it would make more sense to add it to autoproj itself

Agreed!

**Comment by moooeeeep** [comment]
I think this issue was addressed (by https://github.com/rock-core/autoproj/pull/325 ?)

If this is not actually the case, please reopen.
