### ISSUE TITLE
Autoproj does not find `build/env.sh`

### ISSUE THREAD

**Issue by ivan1993br** [rock-core/autoproj#326]
## Problem
When I start a clean workspace and try to update it I have the following error:
```bash
/home/user/.local/share/autoproj/gems/ruby/2.7.0/bundler/gems/autoproj-12d84ac9c127/lib/autoproj/workspace.rb:818:in `initialize': No such file or directory @ rb_sysopen - /home/user/dev/build/env.sh (Errno::ENOENT)
```
As the build folder does not exists because I did not build the environment it raises this error.

## Temporary solution
I did not dig the problem, I just create the `build` folder and it started working. I think that the problem is because on the clean environment the build dir does not exists. (Should it be created a this moment instead of the build one?)

I think it has something to do with this [merge](https://github.com/rock-core/autoproj/pull/322) @doudou . Because of the problematic line, and it has worked before. 

Am I missing something?

**Comment by doudou** [comment]
>  I start a clean workspace 

What's "starting a clean workspace" exactly ?

> I think it has something to do with this merge @doudou . Because of the problematic line, and it has worked before.

Indeed. `export_env_sh` expects the build dir to already exist, which seems to not be the case in some flows. Fixed by #327
