### ISSUE TITLE
Autoproj keeps trying to install python3-dev when a python_package is selected

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#340]

**Comment by chhtz** [comment]
A workaround is to remove the `pkg.internal_dependency "python"` from https://github.com/rock-core/autoproj/blob/49e0bbc7a67627ad002f7202187da4662f7ca2ee/lib/autoproj/autobuild_extensions/dsl.rb#L201
For those who want to patch this locally: The corresponding file is under this path (version numbers may differ for different OS):

    ~/.local/share/autoproj/gems/ruby/2.7.0/gems/autoproj-2.15.0/lib/autoproj/autobuild_extensions

A proper solution would probably be to have the installer check if python is already installed (I did not bother investigating further).
