### ISSUE TITLE
Enable Python by default (and deprecate support for Python 2) ?

### ISSUE THREAD

**Issue by moooeeeep** [rock-core/autoproj#342]
I find it annoying to be asked about USE_PYTHON and the Python version on every bootstrap. Can we make it enabled by default (and don't ask about it instead)? 

Having Python 3 as the default version seems also sensible to me. But maybe someone is still using Python 2. At least it would be great to initiate deprecation, such that we can remove it soonish.

**Comment by doudou** [comment]
:-1: For the record, ruby is enabled by default because autoproj is based on it (so, it's *there*)

Just add `Autoproj.config.set "USE_PYTHON", true` to your buildconf's `init.rb`. Alternatively, if your co-workers don't want that, add it to your $HOME/.autoprojrc

**Comment by planthaber** [comment]
> Just add Autoproj.config.set "USE_PYTHON", true to your buildconf's init.rb. Alternatively, if your co-workers don't want that, add it to your $HOME/.autoprojrc

I could think of this in a package set overrides.rb (enable only if a python_package is in the workspace)
```ruby
has_python_packages=false
Autobuild::Package.each do |name, pkg|
    if pkg.kind_of?(Autobuild::Python)
        has_python_packages=true
    end
end
if has_python_packages==true then
    Autoproj.config.set "USE_PYTHON", true
end
```
Is there a better way than looping over all packages, or can this be done internally by autoproj?

**Comment by moooeeeep** [comment]
> Just add `Autoproj.config.set "USE_PYTHON", true` to your buildconf's `init.rb`.

Thanks for the hint to that option. I tend to forget about these...

I just tried to paste this into [my little test buildconf](https://github.com/moooeeeep/my_buildconf/blob/master/init.rb), but it fails with an error. The same happens when I try to pass these options via `seed-config.yml`:

      installing/updating Python dependencies: opencv-python, pillow
    Command failed
    autoproj: failed in osdeps phase
        'pip install --user pillow opencv-python' returned status 1
        see /path/to/ws/install/log/autoproj-osdeps.log for details
        last 4 lines are:

        Traceback (most recent call last):
          File "/home/moooeeeep/.local/bin/pip", line 7, in <module>
            from pip._internal.cli.main import main
        ModuleNotFoundError: No module named 'pip._internal'

The shims are not created, but the Python user site is adjusted. Thus somehow the Python setup is messed up. Also python2 ist used although I specified to use `/usr/bin/python3`. Am I missing something?

When I leave this unspecified and answer the prompts instead, everything works as expected. Curiously, it will then prompt me about it everytime I run an `aup` though (doesn't it store that info anywhere?).

Can anyone reproduce this, or did I mess up my environment somehow?
