### ISSUE TITLE
autoproj versions uses !binary format when writing yml in ruby 1.9

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#35]
In ruby 1.9, the versions file written by autoproj versions has entries like this:

tag: !binary |-
   c3RhYmxlLTIwMTQwOA==

instead of 

tag: rock1408

same goes for the commit

**Comment by doudou** [comment]
FYI, this is a ruby 1.9 specific issue. Strings that are not encoded as UTF-8 get into this weird format when dumped by YAML.dump

**Comment by doudou** [comment]
should be fixed by ed6f14a12c2901718f6dc4a1a79a449c0eacf109
