### ISSUE TITLE
Autoproj should set cmake paths when a new prefix is added to the environment

### ISSUE THREAD

**Issue by g-arjones** [rock-core/autoproj#350]
Heuristically, just like it does with i.e `PKG_CONFIG_CONFIG_PATH`, `LD_LIBRARY_PATH` and `RUBYLIB`. CMake search paths are well documented here: https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-search-procedure.

Maybe we could do that with `PYTHONPATH` as well. @doudou thoughts?

**Comment by doudou** [comment]
Agreed.
