### ISSUE TITLE
Recent changes make ws.manifest.main_package_set invalid in package sets init.rb

### ISSUE THREAD

**Issue by pierrewillenbrockdfki** [rock-core/autoproj#354]
The changes to configuration.rb in commit c7b291cc5a2c04d828a56105dd1a689ce05e8c85, merged with #335 make ws.manifest.main_package_set nil during execution of package sets init.rb, because the main package set is added last.

Is this change acceptable from autoproj point of view?

This could be fixed by splitting the for loop in two, so the init.rbs get called after all package sets have been re-added.
@2maz

**Comment by pierrewillenbrockdfki** [comment]
Turns out, this is expected behaviour/change.

**Comment by doudou** [comment]
@2maz since we already know what's the main package set, and because the main package set is the one that is being imported first (always), can't we set it anyways ?

**Comment by g-arjones** [comment]
Just out of curiosity why would you want a reference to the main package set in another  package set?

I mean, referencing any package set that is not the current one feels like a bad idea to me

**Comment by pierrewillenbrockdfki** [comment]
DFKI has some custom machinery implemented in a package set that would create new files in autoproj/override.rb. It uses the main_package_set to trigger a reload of these files. As far as i understand, this machinery will be made obsolete by #336 .
