### ISSUE TITLE
Feature discussion: Possibility to auto-apply a seed_config file from the buildconf repo

### ISSUE THREAD

**Issue by planthaber** [rock-core/autoproj#364]
For our CI Pipeline it would be beneficial to store a seed_config.yml in our buildconf repository and to auto-apply it when calling autoproj_bootstrap when the file is present in the buildconf repo.

Currently we have to download the seed_config file first and then call autoproj_bootstrap with the parameter.

I think the best option would be to add a paramater `--seed-config-from-buildconf=PATH`

@doudou What do you think about this idea, or is there already a way to do this? 

I case you think this is possible, we'll try to provide PR for this featue.

FYI: @0Nel @skasperski

**Comment by g-arjones** [comment]
I think the seed configuration is used during install (before checking out the buildconf). Why not use the `init.rb` ?

**Comment by planthaber** [comment]
Yes, you can call autoproj_bootstrap with --seed-config=PATH, but is has to be locally available before calling the script.

I'd like to use it from the "to be checked out" buildconf.

Using the init.rb might be possible, but this will the the default for all bootstraps and not only if set.

One could add an configuration option to the init.rb to ask if defaults should be used though.

Is there a call to load the config seed from the init.rb?

This would solve our issue, as we can then provide a common config_seed via command line for all boostraps on our build server, that just  sets the "load default config_seed option" to true when calling autoproj_bootstrap

**Comment by planthaber** [comment]
> > Yes, you can call autoproj_bootstrap with --seed-config=PATH, but is has to be locally available before calling the script.
> 
> What I meant was that what you are suggesting doesn't sound feasible (at least not without a lot of changes) because autoproj needs the seed configuration before checking the buildconf out so `--seed-config-from-buildconf` doesn't make much sense.
> 
> > One could add an configuration option to the init.rb to ask if defaults should be used though.
> 
> Either that or you can make it dependent on an env var that you would set in your CI or even a constant in the main manifest (then you would have one manifest for the CI and one for development).

But this seed would also be applied after cloning the buidlconf.

As far as i understoot autoproj_bootstrap it installs autoproj and dependencies and then calls 
the bootstrap.rb of the installed autoproj and passes the params here: https://github.com/rock-core/autoproj/blob/master/bin/autoproj_bootstrap#L834

I thought if would only be adding the parameter and then merging the config from the buildconf repo after the buildconf was checked out and before aup is run.
At the same time when the existing config seed is applied (https://github.com/rock-core/autoproj/blob/master/lib/autoproj/cli/bootstrap.rb#L52). All thats needed (as far as I see now) is to copy the file from the buildconf folder instead the one mentioned as config_seed via paramater.

So all i saw that is to be done was: passing the --seed-config-from-buildconf paramater via the bootstrap_options in the last line of autoproj_bootstrap and evaluating it in the bootstrap.rb after cloning the buildconf)


It currently looks like the content is read to the options variable, but in the end only the file name is used to copy the file.
Currently I just wonder if --config-seed values on the options are actually used or if we could change it so one could just set it to an not yet existing file (e.g. "autoproj/config_seed.yml") that will be checked out by bootstrap.rb in the copy.

**Comment by g-arjones** [comment]
So what you are suggesting is that if I want to have a seed-config (to i.e skip the osdeps and git protocol prompts) during install I have to use two seed configurations? Essentialy bootstrap would be `autoproj_bootstrap --seed-config=install_seed.yml --seed-config-from-buildconf=bootstrap_seed.yml ...` is that the proposal?

**Comment by doudou** [comment]
I'm leaning on @g-arjones's side here. The init.rb is essentially the first thing that is read while bootstrapping, so I don't see the point of adding even more flags to autoproj_bootstrap when existing mechanisms can deal with it.

`--seed-config` exists *because* there is the necessity to set configuration from *outside* the buildconf. For everything else, I don't see it.

Use an envvar to enable/disable and then load your YAML config in init.rb

**Comment by planthaber** [comment]
> So what you are suggesting is that if I want to have a seed-config (to i.e skip the osdeps and git protocol prompts) during install I have to use two seed configurations? 

Actually it would be `--no-interactive --seed-config-from-buildconf=bootstrap_seed.yml`

Using the init.rb and envvar also seems feasible if it is possible to do that in a package_set, otherwise we would need to modify/maintain all out buildconfs to use the functionality.
But I guess this would have to be done in the init.rb of the rock.core package set before any other package_set (with config options in their init.rb)

But the build server could inject the init.rb code after autoproj_bootstrap with --no-interactive and before callung the initial aup though.

**Comment by planthaber** [comment]
Yes, but not to also maintain the code in the init.rb

**Comment by g-arjones** [comment]
It's just a bunch of "set" calls. Not too different from a yml file in my opinion

**Comment by doudou** [comment]
- you can't implement that functionality in a package set, since you need the configuration to bypass prompts related to checking out the package set themselves.
- doing it is essentially `Autoproj.config.load PATH`

I was going to say that I could live with the argument (I could use the functionality myself ...), but then I would also need to implement support for multiple manifests (placeholders ?). It feels like something that's best supported by actual code (a.k.a. the init.rb solution)

I prefer the init.rb solution much better. You *will* have to modify each buildconf anyways to add the config file, you can add the three lines of code necessary to load it.

**Comment by planthaber** [comment]
Ok, thanks for the discussion and opinions.

I still did not unserstand why the config is parsed, and then bootstrap.rb just copies the file into .autoproj/config.yml. I whould have guessed. If it wouldn't pe parded in autopro_bootstap, one could use --seed-config=auroproj/config_seed.yml with an nonexistent file and bootstrap.rb would copy it to .autoproj/config.yml after checking out the buildconf (current behavior).

Nevertheless, I guess we'll use the init.rb approach for the buidlserver and inject the call to the init.rb:

* autoproj_bootrap with --non-interactive 
* echo "Autoproj.config.load 'autoproj/seed.yml'" >> autoproj/init.rb
* autoproj update

**Comment by planthaber** [comment]
FYI: the init.rb code

```ruby
# this needs to be called before the git server configuration in the init.rb
# to init the server config before questions are asked
if ENV["CONFIG_SEED_FROM_BUILDCONF"] != "" then
    seed_file = ENV['AUTOPROJ_CURRENT_ROOT'] + "/" + ENV['CONFIG_SEED_FROM_BUILDCONF']
    Autoproj.message "using config seed file: #{seed_file}"    
    Autoproj.config.load(path: seed_file)
end
```

**Comment by planthaber** [comment]
@doudou This is the current implementation to add a default config, I think doing it this way is far less intrusive as the initilal idea. Do you think, we can add this function to autoproj? It cannot be added to package_sets, as they are loaded after the init.rb of the buildconf on bootstrap. But is solves our issue as we can just use --no-interactive to apply the config seed.

If you agree to put it directly into autoproj, what would be the preferred location? 
* extra file similar to git_server_configuration.rb
* lib/autoproj/configuration.rb?

I'd be happy to create the PR for this.

```ruby
# allows to load a seed-config.yml file from a buildconf repository
# rather than providing it before checkout using the --seed-config paramater
# of the autoproj_bootstrap script
# this allows to bootstrap with --no-interactive and still apply a custom config e.g. in CI/CD
# The call to this function has to be in the init.rb of the buildconf BEFORE any other
# config option, e.g. the git server configuration settings
# The filename parameter is the name of the config seed yml file in the repository
def define_default_config_seed_in_buildconf(filename)
    Autoproj.configuration_option 'use_default_config', 'boolean',
    :default => "yes",
    :doc => ["Should the default workspace config be used?", "This buildconf denines a default configuration", "Should it be applied?"]
    if (Autoproj.user_config('use_default_config')) then
        unless Autoproj.config.has_value_for?('default_config_applied')
            seed_config = File.join(Autoproj.workspace.root_dir, 'autoproj', filename)
            Autoproj.message "loading seed config #{seed_config}"
            Autoproj.config.load(path: seed_config)
            Autoproj.config.set 'default_config_applied', true, true
        end
    end
end
```

**Comment by doudou** [comment]
Hi @planthaber. No objection to add it to autoproj, I'll comment on the code in the pull request.

I think the best spot to put it would be as a singleton method in Configuration. 

- One thing I do not like is having yet another question presented to the user. I would prefer to keep the configuration option (and the associated question) out of the method, and then a better name for it would be `load_config_once`.
- You will also have to make it robust to being called multiple times for different filenames (because that API calls for someone calling it with different files).

**Comment by planthaber** [comment]
I see the issue with "yet another question", but mostly this will result in less questions if a default is given in the config seed.

As it is ok to be incomplete for the seed_config, e.g. in the rock buildconf we could already add the github, rtt_target, rtt_corba_implementation and possibly the odep_mode and apt_dpkg_update to the default_seed and this shrink 5 questions into one. 

I separated it into two calls with and without question:

https://github.com/rock-core/autoproj/pull/372
