### ISSUE TITLE
autoproj update should only revert to older commit if explicitely asked to

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#37]
Currently autoproj update will happily revert to the given commit. This is not what one would normally want, but it should only go up in the commits unless explicitely asked.

**Comment by doudou** [comment]
I think you mean autoproj update, right ?

**Comment by doudou** [comment]
Some thoughts

Basically, implementing this change means that "pinning" a package (with tag, commit ID or in subversion with a revision) is interpreted as "what should be merged locally". I.e. a commit ID has the same meaning that a branch in git.

Which leads to two the following question:

When resetting with e.g. git, should we also reset even if only the branch is given ? (I would say yes)

**Comment by jakobs** [comment]
Sorry, I don't understand the question properly. 
If a branch is pinned, update will do:
* nothing if remote is in history of the local branch
* forward to remote if current head is in history of remote
For tags/commitids:
* nothing if tag is in history of local head
* forward to tag if head is in history of tag

Did I miss anything?

**Comment by doudou** [comment]
Yes. You're describing the operation when "reset" is not requested. However, to be consistent, we should probably change the behaviour when reset is requested in the 'branch' case to:

If a git importer is configured to track a branch, then:
  - reset the local branch to the current status of the remote branch if reset is given

**Comment by doudou** [comment]
Oh, by the way, I'm on it.

**Comment by doudou** [comment]
Done for git and svn on the versioning branch. I'm closing this one for now
