### ISSUE TITLE
autoproj bootstrap fails to find bundler on ubuntu 22.04

### ISSUE THREAD

**Issue by annaborn** [rock-core/autoproj#377]
Hello Sylvain @doudou!

I just tried to run bootstrap on ubuntu 22.04 and I got this error message. Have you already seen this?

```
ruby autoproj_bootstrap git https://github.com/rock-core/buildconf.git
Detected 'gem' to be /usr/bin/gem3.0
Installing bundler in /home/dockeruser/.local/share/autoproj/gems/../.local/share/gem/ruby/3.0.0
Successfully installed bundler-2.3.18
1 gem installed
gem install bundler returned successfully, but still cannot find bundler in /home/dockeruser/.local/share/autoproj/gems/../.local/share/gem/ruby/3.0.0
```

**Comment by doudou** [comment]
I haven't tried yet. Autoproj/rock's ruby bits are probably not compatible with Ruby 3.x (yet)

**Comment by moooeeeep** [comment]
FWIW: We had the same error in our `debian:testing` CI build in the beginning of the year, when they still provided Ruby version 2.7:

    Detected 'gem' to be /usr/bin/gem2.7
    Installing bundler in /root/.local/share/autoproj/gems/../.local/share/gem/ruby/2.7.0
    Successfully installed bundler-2.2.33
    1 gem installed
    gem install bundler returned successfully, but still cannot find bundler in /root/.local/share/autoproj/gems/../.local/share/gem/ruby/2.7.0

Now they upgraded to Ruby 3.0 and the error persists.

**Comment by moooeeeep** [comment]
After a quick test, it seems to be fixed with [this version](https://raw.githubusercontent.com/rock-core/autoproj/master/bin/autoproj_bootstrap) already.

Maybe the bootstrap script [available here](https://www.rock-robotics.org/autoproj_bootstrap) just needs to be updated?

**Comment by planthaber** [comment]
> After a quick test, it seems to be fixed with [this version](https://raw.githubusercontent.com/rock-core/autoproj/master/bin/autoproj_bootstrap) already.
> 
> Maybe the bootstrap script [available here](https://www.rock-robotics.org/autoproj_bootstrap) just needs to be updated?

You can update it via PR here:
https://github.com/rock-core/rock-core.github.io/tree/master/downloads

**Comment by moooeeeep** [comment]
This is a related issue then, I guess: https://github.com/rock-core/rock-core.github.io/issues/8
