### ISSUE TITLE
Error message for autoproj update not correct

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#40]
This error message is also thrown when the asked for commit is not on the branch, even though that branch *is* actually on a remote:
"branch master of xxx contains commits that do not seem to be present on the remote repository. I can't go on as it would mean losing some stuff. Push your changes or reset to the remote commit manually before trying again"

We should either change the message to be correct, or adapt the test.

**Comment by doudou** [comment]
Can you be more explicit ? I kind-of guess the situation, but can't see it clearly.

**Comment by doudou** [comment]
@jakobs: I'm still not getting the problem

**Comment by doudou** [comment]
@jakobs: ping again ... will have to ignore it if I don't get more information

**Comment by jakobs** [comment]
The error suggests that the requested commit is not on the remote repository. However, I had cases where the commits where there, but just on a different branch.

**Comment by doudou** [comment]
@jakobs: can you have a look at the updated message in rock-core/autobuild#18 ?
