### ISSUE TITLE
make .git suffix in repo url optional

### ISSUE THREAD

**Issue by annaborn** [rock-core/autoproj#400]
Hello  Sylvain @doudou.

Can we make a .git suffix in repo url optional? The repositories in azure devops does not follow the standards, so their repo url does not have .git at the end. We have now a trouble to checkout the azure repos.
I mean this line
https://github.com/rock-core/autoproj/blob/47e93f159d7053c99e8b6f93139da11b56e695cb/lib/autoproj/git_server_configuration.rb#L103

Does .git suffix required anyway? Since the checkout/push/pull in gitlab and github seems to work also without .git.

We can provide a pull request, just need to know what solution would be accepted. :)

Thank you in advance!

**Comment by doudou** [comment]
It's a bit meaningless, the best would obviously to just tell everyone to add `.git` to their URL if they need it, but it's always trick to change existing behavior.

I think the best would be to add a `suffix` parameter, that would be ".git" by default, and allow `nil` to disable the feature ?
