### ISSUE TITLE
Problem with 'find_in_path'

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#43]
On the current versioning branch, I get the following error whenever I try to do anything.
The offending commit seems to be a01a61c7dad64903458e3c66d80343c920877024, the error goes away when I revert it.

/home/jakob/dev/wally/tools/autoproj/lib/autoproj/system.rb:76:in `find_in_path': cannot find ruby1.9.1 in PATH (/home/jakob/dev/wally/install/bin:/home/jakob/dev/wally/.gems/bin) (ArgumentError)
	from /home/jakob/dev/wally/autoproj/remotes/orocos.toolchain/orocos.autobuild:83:in `block in <top (required)>'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/autobuild.rb:408:in `block in cmake_package'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:318:in `[]'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:318:in `block (2 levels) in finalize_package_setup'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:317:in `each'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:317:in `block in finalize_package_setup'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:316:in `each_value'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:316:in `finalize_package_setup'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:1547:in `initialize_and_load'
	from /home/jakob/dev/wally/tools/autoproj/bin/autoproj-envsh:8:in `block (2 levels) in <top (required)>'
	from /home/jakob/dev/wally/tools/autobuild/lib/autobuild/reporting.rb:14:in `silent'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:24:in `silent'
	from /home/jakob/dev/wally/tools/autoproj/bin/autoproj-envsh:6:in `block in <top (required)>'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:1621:in `block in report'
	from /home/jakob/dev/wally/tools/autobuild/lib/autobuild/reporting.rb:282:in `report'
	from /home/jakob/dev/wally/tools/autoproj/lib/autoproj/cmdline.rb:1620:in `report'
	from /home/jakob/dev/wally/tools/autoproj/bin/autoproj-envsh:5:in `<top (required)>'
	from /home/jakob/dev/wally/tools/autoproj/bin/autoproj:35:in `load'
	from /home/jakob/dev/wally/tools/autoproj/bin/autoproj:35:in `<main>'

**Comment by doudou** [comment]
This looks like PATH is reset to empty the first time env_push_path is called.

**Comment by doudou** [comment]
I did not have it because I always call set_initial_env

**Comment by doudou** [comment]
Should be fixed now

**Comment by jakobs** [comment]
cool, thanks!
