### ISSUE TITLE
autoproj should handle multiple remotes

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#45]
It would be great if autoproj could handle different remotes. This is very useful when cloning repos. Not exactly shure how this would work. The problem is that currently I have to change the remote manually when I want to change the clone back to the original repo.

**Comment by doudou** [comment]
Could you describe the workflow you want to achieve in more details ?

**Comment by doudou** [comment]
Autoproj 2.0 has something like this: it creates one remote per package set, pointing to the URL that the package set own overrides sets (i.e. if you have rock.core and my.project with my.project adding an override, the rock.core remote will point to mainline and the my.project remote will point to the overriden URL). 'autobuild' always points to the final VCS.
