### ISSUE TITLE
autoproj commit for package selection

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#46]
when I do autoproj version for a package selection, e.g.
`autoproj versions base/types`
I get a list of package. However, when I try the same thing for commit
`autoproj commit base/types`
I get 
`error: pathspec 'base/types' did not match any file(s) known to git.`

**Comment by doudou** [comment]
autoproj-commit is currently very bare-bone and passes its arguments to git commit. This is a duplicate of #42
