### ISSUE TITLE
autoproj versions package selection --no-deps

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#47]
When I do 
`autoproj versions --no-deps base/types`
I get an error. 
tools/autoproj/lib/autoproj/cli/versions.rb:64:in `parse_options': invalid option: --no-deps (OptionParser::InvalidOption)

**Comment by doudou** [comment]
Yes, it is currently unsupported as --help would have shown you. Retagged as post-versioning

**Comment by doudou** [comment]
implemented on v2

```
autoproj versions base/types --deps=f
```
