### ISSUE TITLE
Bootstrapping using master branch of autoproj 

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#49]
It would be greate if there was a way to bootstrap using the latest version of autoproj.

**Comment by doudou** [comment]
There was already a way, do prerelease gems and use the AUTOPROJ_USE_PRERELEASE envvar. If you want the latest latest, run

```
rake dist:package
```

Then bootstrap with
  autoproj_bootstrap localdev [normal options]

and install the locally-generated autoproj gem manually
