### ISSUE TITLE
Alternative manifests

### ISSUE THREAD

**Issue by jakobs** [rock-core/autoproj#50]
In a project there are often multiple deployment targets. E.g. desktop, robot, maybe build server, that have a different manifest structure. It would be great if one could specify multiple manifest files, and tell autoproj as a config variable which one to use.

**Comment by goldhoorn** [comment]
Why not simply combine the layout section of your manifests?

**Comment by jakobs** [comment]
I don't understand what you mean by that.

**Comment by goldhoorn** [comment]
For this use case you explain, why do you not combine the two one manifest into one.
Copy all entries from the first manifest to the second manifest, by doing this you should get what you want. But it could result in the following problems (thats why i'm vote against a general tooling)

The problem i see with automatic tooling that the package sets might influence each other or be incompatible (overrides, different definitions...) this could result in a unclear behavior. I already had this as i tried to bootstrap avalon<->dagon together.

**Comment by jakobs** [comment]
I don't have a problem with the manifests being in one, and then supporting different targets. The problem I am trying to tackle is to prevent development packages (e.g. simulator) to end up on the robots, while making sure the problems you mention (inconsistent package sets, overrides, etc) to not come up.

**Comment by doudou** [comment]
This is available on autoproj v2 with the 'manifest' command

Assuming you have multiple manifests under autoproj/:

- autoproj/manifest
- autoproj/manifest.simulation

one can select the simulation manifest with

```
autoproj manifest autoproj/manifest.simulation
```

or the shortcut

```
autoproj manifest simulation
```
