### ISSUE TITLE
autoproj_boostrap (prerelease): cannot read file / URL 

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#57]
if the environment variable AUTOPROJ_USE_PRERELEASE is set to 1 the boostrap process exits with the following error message:

    cannot read file / URL git@git.hb.dfki.de:wally/buildconf.git, did you mean 'autoproj bootstrap      VCSTYPE git@git.hb.dfki.de:wally/buildconf.git' ?
    ERROR: failed to run autoproj bootstrap git@git.hb.dfki.de:wally/buildconf.git

It seems that someone is swallowing 'git' because the following command succeeds (2x git):
   ruby autoproj_bootstrap git git git@git.hb.dfki.de:wally/buildconf.git

**Comment by doudou** [comment]
When using autoproj_bootstrap, you're supposed to add a 'dev' option (which is probably why the argument gets swallowed)

**Comment by doudou** [comment]
Fixed by e2979722a62b0ebcb8148c0d867f4357ad66a8df
