### ISSUE TITLE
autoproj ignores package manfiest.xml  (prerelease)

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#58]
autoproj does not check the dependencies of a package listed in its package/manifest.xml  if the package is directly added to the layout section in autoproj/manifest.xml.

**Comment by doudou** [comment]
can you be more specific ? What you did, what happens, what you expected.

**Comment by D-Alex** [comment]
By calling "amake XYZ" I expect autoproj to pull in all dependent packages listed in XYZ/manifest.xml and builds them before triggering the build for XYZ. This does not happen if XYZ is directly listed in the autoproj/manifest.xml (section layout). Also if an unknown packages is listed in the XYZ/manifest.xml autoproj does yell in this particular  case.

**Comment by doudou** [comment]
Got it.

This is a bad and unexpected consequence of another feature ... That you can force building an excluded package by adding it explicitly in the layout. Since missing dependencies are handled by the exclusion mechanism, it also covers those.

Will have to add a special marking in the manifest to force the build of the package.

I see two options:
 - introduce a new section (e.g. force_build)
 - add a ! marking on packages in the layout

**Comment by doudou** [comment]
I can't reproduce the problem with autoproj not checking out dependencies. Note that not installing osdeps is expected behaviour (albeit an annoying one) as osdeps are pretty costly to check.

**Comment by D-Alex** [comment]
To reproduce the problem just add an unknown dependency to a package directly listed in the manifest

    layout
     - image_processing/frame_helper

in the frame_helper/manifest.xml
    
     <depend package="image_processing/unknown" />

amake image_processing/frame_helper is not yelling and builds the package. This is not the case if the package is removed from the layout.

**Comment by doudou** [comment]
I could reproduce that. But you also mention that dependencies are not built and/or checked out before the packages that depend on them. That's what I could not reproduce.

**Comment by D-Alex** [comment]
I cannot reproduce it either but I will keep an eye on this. 

Concerning the force_build,  how about adding a flag to autoproj (amake) signalizing that dependencies are ignored. Also, I would print an information for the user after a package build failed that he can force the build with amake --force-build.

**Comment by doudou** [comment]
> Concerning the force_build, how about adding a flag to autoproj (amake) signalizing that dependencies are ignored.
Yes, autoproj should want the user that the package should not be built but will be anyways. However, this goes with the force_build or ! marker, not in replacement of (or ?)

> Also, I would print an information for the user after a package build failed that he can force the build with amake --force-build.
If the builds fails, he/she should not have to use --force
