### ISSUE TITLE
autoproj-1.13.1: current_import_state': undefined method `show' 

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#61]
calling autoproj update results in the following error message:

autoproj-1.13.1/lib/autoproj/ops/snapshot.rb:169:in current_import_state': undefined methodshow' for nil:NilClass (NoMethodError)

I looked into the code and I think it cannot be assumed that main.importer is returning an object.

The vhs which has no importer is (the git is a clone from another git on the hard disk):
local:/var/lib/jenkins/workspace/ropencv_gem/dev/autoproj

same propblem here:
gems/autoproj-1.13.1/lib/autoproj/ops/snapshot.rb:191:in save_import_state': undefined methodgit_dir' for nil:NilClass (NoMethodError)

**Comment by doudou** [comment]
Can you try https://github.com/rock-core/autoproj/pull/62/ ?

**Comment by D-Alex** [comment]
I installed the gem from the #62 (rake dist:gem; gem install pgk/autoproj-1.13.1.gem) and now I get the following errer after calling autoproj update:

    ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/package_set.rb:402:in `vcs_field': undefined method `[]' for nil:NilClass (NoMethodError)

**Comment by doudou** [comment]
Mmmmm ... weird. I've tested it against something looking like just your use case (running autoproj update with a cloned autoproj buildconf without "telling" about the VCS to autoproj) 

I would need the full backtrace (call autoproj with --debug)

**Comment by D-Alex** [comment]
No much different to the original output:

    XXXXX@XXXXXX:~/workspace/ropencv_gem/dev$ autoproj update --debug
    How should I interact with gitorious.org (http, ssh): http
    How should I interact with github.com (git, http, ssh): http
    Which prepackaged software (a.k.a. 'osdeps') should autoproj install automatically (all, none or a comma-separated list of: os gem pip) ? all
    operating system: ubuntu,debian - 14.04,14.04.2,lts,trusty,tahr
    looking for RubyGems updates                                       
    autoproj: loading ...
    run 'autoproj reconfigure' to change configuration options
    and use 'autoproj switch-config' to change the remote source for
    autoproj's main build configuration
    /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/package_set.rb:402:in `vcs_field': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/package_set.rb:398:in `version_control_field'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/package_set.rb:511:in `block in importer_definition_for'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/base.rb:22:in `in_file'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/package_set.rb:510:in `importer_definition_for'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/manifest.rb:469:in `importer_definition_for'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/manifest.rb:504:in `block in load_importers'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/manifest.rb:503:in `each_value'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/manifest.rb:503:in `load_importers'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/cmdline.rb:233:in `load_configuration'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/bin/autoproj:93:in `block in <top (required)>'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/cmdline.rb:1605:in `block in report'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autobuild-1.9.0/lib/autobuild/reporting.rb:282:in `report'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/lib/autoproj/cmdline.rb:1604:in `report'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/gems/autoproj-1.13.1/bin/autoproj:47:in `<top (required)>'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/bin/autoproj:23:in `load'
	from /var/lib/jenkins/workspace/ropencv_gem/dev/.gems/bin/autoproj:23:in `<main>'

**Comment by doudou** [comment]
Yes, different, it's not in the update log handling anymore

**Comment by doudou** [comment]
In which package set does this fail (PackageSet#name returns the name) ? Is there anything "special" about this package set ?

**Comment by D-Alex** [comment]
It is the local package set defined in the autoproj folder. The name method returns "main configuration"

The source code can be found here (it is basically only installing opencv):
https://github.com/D-Alex/ropencv_jenkins/tree/gem

**Comment by doudou** [comment]
I've updated #62, can you test again ?

**Comment by D-Alex** [comment]
:+1:  works

**Comment by doudou** [comment]
PR got merged and included in 1.13.2. Please test and reopen this issue if the problem persists.
