### ISSUE TITLE
Build osdeps from source

### ISSUE THREAD

**Issue by phyrog** [rock-core/autoproj#64]
Is it still possible to build osdep packages from source, like suggested in [samples/osdeps.yml](https://github.com/rock-core/autoproj/blob/master/samples/osdeps.yml#L45-L54)?

This would be very useful for Arch support, since some dependencies only exist in the [AUR](https://aur.archlinux.org/) and are installable only from source.

**Comment by goldhoorn** [comment]
The correct way should be like opencv:

Take a look to: https://github.com/rock-core/package_set/blob/master/06osdeps_from_source.autobuild

By doing so you can competently define how and where packages are build.

**Comment by phyrog** [comment]
So the basic workflow with the AUR would be to download the PKGBUILD file (via wget or curl), run `makepkg` to compile and then `pacman -U <output file>` to install the package.

How what kind of package would I use for that? cmake_package does not seem right for that.

Another possiblity might be to replace pacman as the package manager by yaourt, which is not the standard package manager on Arch, but is able to install packages from the AUR directly. This would be very much like the support for mac osx and homebrew (which is also not the default package manager).

**Comment by phyrog** [comment]
Used the way suggested by @goldhoorn, so I'll close this issue.
