### ISSUE TITLE
Bug: "`root_dir': not in a Autoproj installation" in the middle of updating

### ISSUE THREAD

**Issue by planthaber** [rock-core/autoproj#65]
Hi,

Our buildserver got the masage "`root_dir': not in a Autoproj installation" in the middle of updating after several updated were executed, no idea why this happend.

> updated drivers/camera_firewire
  updating drivers/camera_interface
  updated drivers/camera_interface
  updating drivers/camera_usb
  updated drivers/camera_usb
  updating drivers/canbus
  updated drivers/canbus
/data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/system.rb:48:in `root_dir': not in a Autoproj installation (Autoproj::UserError)
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/system.rb:66:in `config_dir'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/package_set.rb:596:in `raw_local_dir'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/package_set.rb:135:in `create_autobuild_package'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/ops/snapshot.rb:155:in `import_state_log_package'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/ops/snapshot.rb:34:in `update_log_available?'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/cmdline.rb:776:in `ensure in import_packages'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/cmdline.rb:782:in `import_packages'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/bin/autoproj:198:in `block in <top (required)>'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/cmdline.rb:1605:in `block in report'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autobuild-1.9.0/lib/autobuild/reporting.rb:282:in `report'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/lib/autoproj/cmdline.rb:1604:in `report'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/gems/autoproj-1.13.2/bin/autoproj:47:in `<top (required)>'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/bin/autoproj:23:in `load'
	from /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/master/node/Ubuntu_current/dev/.gems/bin/autoproj:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by doudou** [comment]
Would look like someone is chdir()-ing outside of the workspace.

**Comment by planthaber** [comment]
Saw this happen only once, just wanted ro report "in case" this is not the error of a single package.
