### ISSUE TITLE
v1.13.2: rebuild fails because of restoring gems outside of the installation

### ISSUE THREAD

**Issue by D-Alex** [rock-core/autoproj#68]
Calling autoproj rebuild on the command line fails because of the following error. What I do not understand in the first place. Why is autoproj restoring gems during rebuild? They are not supposed to be altered. And if they are I would assume the guy knows what he is doing.

As workaround I uninstalled all global gems used by the installation  :unamused: 
   
    autoproj: failed in osdeps phase
    '/usr/bin/ruby2.1 -S gem2.1 pristine --extensions hoe hoe-yard thin grape rack-cors faye-websocket sprockets rake-compiler websocket activesupport bundler cucumber rice kramdown rbtree binding_of_caller hooks ffi' returned status 1
    see /home/aduda/dev/rock_master/install/log/autoproj-osdeps.log for details
    last 10 lines are:

    Restored cucumber-2.0.0
    Building native extensions.  This could take a while...
    Restored rice-1.7.0
    Restored kramdown-1.7.0
    Building native extensions.  This could take a while...
    Restored rbtree-0.4.2
    Building native extensions.  This could take a while...
    ERROR:  While executing gem ... (Gem::FilePermissionError)
        You don't have write permissions for the /var/lib/gems/2.1.0 directory.

**Comment by doudou** [comment]
This got added in case rebuild is called after an OS upgrade or change of ruby version (one of the most common cases). In these cases, even the gems extensions need to be rebuilt.

The --no-osdeps option should allow you to disable that. Because of this bug, we might have to do the reverse and only optionally enable it.

**Comment by D-Alex** [comment]
Fair point. But for me a bit too much magic. I would rather go into the direction of an assistant which can be called in cases where the build is corrupted. Each package set can add scripts for checking the status of its packages. 

autoproj doctor
warning qtruby seems broken. This can happen after updating qt. Shall I reinstall qtruby?

**Comment by goldhoorn** [comment]
:-1: keep it as it is not more option that only saves time. No new user will ever use them, but many will thank you to repair automatically.
