### ISSUE TITLE
Autoproj fails to update if overrides.d is a submodule

### ISSUE THREAD

**Issue by jmachowinski** [rock-core/autoproj#70]
If overrides.d is a git submodule, one gets a strange error : 
2015-05-07 13:40:36 +0200: running
    git --git-dir /home/scotch/entern/autoproj/.git update-index --add --cacheinfo 100644 0a6a539e65f504d2cc808be95a6c4c8a226e896a overrides.d/50-versions.yml
in directory /home/scotch/entern
error: 'overrides.d/50-versions.yml' appears as both a file and as a directory
error: overrides.d/50-versions.yml: cannot add to the index - missing --add option?
fatal: git update-index: --cacheinfo cannot add overrides.d/50-versions.yml

I'm puzzled by this one, it looks like a snapshot is generated, even thou I did not request this.

**Comment by doudou** [comment]
autoproj does by keeping a log of all updates. I don't personally plan to support having overrides.d as a submodule, but feel free to propose a working patch in this direction.

**Comment by doudou** [comment]
Closing this ... See above for reason.
