### ISSUE TITLE
overrides.d fails to override release with master

### ISSUE THREAD

**Issue by planthaber** [rock-core/autoproj#77]
Hi, we need base/orogen/std to be on master (for orogen_metadata), but want the rest on the release.
On aup --all the checkout fails with

>Command failed               
base/orogen/std(/home/planthaber/dfki/rock/entern/base/orogen/std): failed in import phase
    the local branch 'master' and the remote branch master of base/orogen/std have diverged, and I therefore refuse to update automatically. Go into /home/planthaber/dfki/rock/entern/base/orogen/std and either reset the local branch or merge the remote changes

The overrides.d fails if 25-release.yml sets a tag and the override sets a branch. It looks like the .yml files are executed after each other rather than merging them before doing the checkouts.

**Comment by planthaber** [comment]
is this related to https://github.com/rock-core/autobuild/issues/22

**Comment by doudou** [comment]
You have to set the tag to nil explicitely when overriding a tag

~~~
base/orogen/std:
  branch: master
  tag: ~
~~~

**Comment by doudou** [comment]
Actually, in this particular case, this is just autoproj telling you the truth

Both branches have diverged, you have to reset explicitely. That's exactly the situation here and there's no way this behaviour will change.

The issue here is that rock-15.05 should be merged in base/orogen/std with -m ours

**Comment by planthaber** [comment]
Thats true, but even on a new bootstrap this issue occurs.

I think this is quite confusing to not so experienced users when someone else changes the default in a buildconf resulting in updating AND new checkouts failing. because "master" and "master" diverged.

**Comment by planthaber** [comment]
looks like the same issue arises when the release tag is used on bootstrapping

@goldhoorn is looking into this:

>+ /usr/bin/ruby2.1 ../autoproj_bootstrap --no-color --no-progress git https://github.com/rock-core/buildconf.git tag=rock-15.05
  autodetecting the operating system
  operating system: debian - 8,jessie
autoproj: installing a proper Ruby environment (this can take a long time)
    Which prepackaged software (a.k.a. 'osdeps') should autoproj install automatically (all, none or a comma-separated list of: os gem pip) ? all
autoproj: installing autoproj and its dependencies (this can take a long time)
    looking for RubyGems updates
  operating system: debian - 8,jessie
  Which prepackaged software (a.k.a. 'osdeps') should autoproj install automatically (all, none or a comma-separated list of: os gem pip) ? os,gem,pip
  looking for RubyGems updates
sourcing autoproj shell helpers
add "Autoproj.shell_helpers = false" in autoproj/init.rb to disable
  checking out autoproj main configuration
  checkout of autoproj main configuration failed, deleting the source directory /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/rock-15.05/node/Debian_stable/dev/autoproj
  ERROR: switching configuration failed: autoproj main configuration(/data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/rock-15.05/node/Debian_stable/dev/autoproj): failed in import phase
    the local branch 'master' and the remote branch master of autoproj main configuration have diverged, and I therefore refuse to update automatically. Go into /data/jenkins/workspace/workspace/rock-complete-incremental/Flavor/rock-15.05/node/Debian_stable/dev/autoproj and either reset the local branch or merge the remote changes
autoproj bootstrap failed

**Comment by goldhoorn** [comment]
I close this PR here because it is a issue from autobuild see https://github.com/rock-core/autobuild/issues/24
