### ISSUE TITLE
Archive importer will delete a local archive if import fails

### ISSUE THREAD

**Issue by vbargsten** [rock-core/autoproj#86]
By accident I created a gzip tarball with .bz2 extension (using git archive). Using autoproj (aup my_lib), the import fails of course. However, the source file is silently deleted afterwards. I verified this behaviour. The tar -xjf ... command found in the import log does not delete the file if executed independently.

On successful import the file is still there.

I use a source definition like this:
  - my_lib:
    type: archive
    url: 'file://$HOME/src/my_lib.tar.bz2'
    archive_dir: my_lib
    update_cached_file: false

**Comment by doudou** [comment]
should be fixed in the just released autobuild 1.9.2. Just update to get it.
