### ISSUE TITLE
Check permissions for file system

### ISSUE THREAD

**Issue by skasperski** [rock-core/autoproj#89]
In a current case bootstrapping failed because the used partition was mounted with the "noexec" flag, so nothing could be executed from there. Such errors are very hard to identify, so it would be nice if autoproj could initially check whether all file system permissions are set correctly.

**Comment by doudou** [comment]
I really don't believe that it's autoproj job to handle weird system setup, really. If you're "smart" enough to have partitions mounted with noexec, then you should also be smart enough to realize that you can't install things meant to be executed there.
