### ISSUE TITLE
autoproj2.0: on the rock-core package set no packages are build

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autoproj#91]
The default manifest with:
- rock.core 

and ```autoproj build ``` does nothing, it only checks out the package sets.

calling autoproj build rock.core helps but it is not what (i thougt) it should do

**Comment by goldhoorn** [comment]
if calling with rock.core package like external/opencv are build. Is this intended now?

**Comment by doudou** [comment]
Is that a clean bootstrap ? I don't have these issues at all bootstrapping rock-core/buildconf on ubuntu 14.04 and ruby 2.0 (and never had it on my "work" workspaces)

**Comment by goldhoorn** [comment]
Its a clean bootstrap yes,
debian stable and ruby2.1

On 21.10.2015 17:38, Sylvain Joyeux wrote:
>
> Is that a clean bootstrap ? I don't have these issues at all
> bootstrapping rock-core/buildconf on ubuntu 14.04 and ruby 2.0 (and
> never had it on my "work" workspaces)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/91#issuecomment-149935314>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
- "debian stable" could explain the opencv thing if there is an issue with autodetection (i.e. if opencv is still marked as nonexistent for it)
 - the rest ? Don't know. I can't reproduce.

**Comment by goldhoorn** [comment]
Funny maybe this BT helps you to give me a better hint?

Status recognizeses that the (needed?) packages are not importent, but update does nothing?

```
goldhoorn@mgoldhoorn:~/bootstraps/all/dev$ autoproj status
autoproj: displaying status of configuration
main configuration, orocos.toolchain, rock.core, rock, rock.tutorials, rock.simulation: local and remote are in sync
main configuration:   failed to fetch status information (main configuration(/home/goldhoorn/bootstraps/all/dev/autoproj): failed in import phase
    failed to find the merge-base between HEAD and . Are you sure these commits exist ?)
main configuration: local and remote are in sync

autoproj: displaying status of packages
base/cmake:   is not imported yet
base/console_bridge:   is not imported yet
base/numeric:   is not imported yet
base/orogen/std:   is not imported yet
base/orogen/types:   is not imported yet
base/scripts:   is not imported yet
base/templates/bundle:   is not imported yet
base/templates/cmake_lib:   is not imported yet
base/templates/cmake_vizkit_widget:   is not imported yet
base/templates/doc:   is not imported yet
base/templates/ruby_lib:   is not imported yet
base/templates/vizkit3d_plugin:   is not imported yet
base/types:   is not imported yet
bundles/rock:   is not imported yet
drivers/aggregator:   is not imported yet
drivers/orogen/aggregator:   is not imported yet
drivers/orogen/transformer:   is not imported yet
drivers/transformer:   is not imported yet
external/sisl:   the ArchiveImporter importer does not support status display
gui/rock_webapp:   is not imported yet
gui/rock_widget_collection:   is not imported yet
gui/vizkit:   is not imported yet
gui/vizkit3d:   is not imported yet
perception/frame_helper:   is not imported yet
perception/jpeg_conversion:   is not imported yet
tools/class_loader:   is not imported yet
tools/log_tools:   is not imported yet
tools/logger:   is not imported yet
tools/orocos.rb:   is not imported yet
tools/orogen_metadata:   is not imported yet
tools/pocolog:   is not imported yet
tools/pocolog_cpp:   is not imported yet
tools/rest_api:   is not imported yet
tools/roby:   is not imported yet
tools/rubigen:   is not imported yet
tools/service_discovery:   is not imported yet
tools/syskit:   is not imported yet
tools/telemetry:   is not imported yet
goldhoorn@mgoldhoorn:~/bootstraps/all/dev$ autoproj update
  WARN: gitorious_server_configuration is deprecated, use require 'git_server_configuration' and Autoproj.git_server_configuration instead
  WARN: note that the method call interface has not changed, you just have to change the name(s)
  WARN: gitorious_server_configuration is deprecated, replace by git_server_configuration
  WARN: Note that the call interface has not changed, you only need to change the method name
  WARN: gitorious_server_configuration is deprecated, replace by git_server_configuration
  WARN: Note that the call interface has not changed, you only need to change the method name
  operating system: debian - 8,jessie
  bundler: connected to https://rubygems.org/
  updated autoproj main configuration        
  WARN: gitorious_server_configuration is deprecated, replace by git_server_configuration
  WARN: Note that the call interface has not changed, you only need to change the method name
  WARN: gitorious_server_configuration is deprecated, replace by git_server_configuration
  WARN: Note that the call interface has not changed, you only need to change the method name
autoproj: updating remote definitions of package sets
  updated rock.core        
  updated rock            
  updated rock.tutorials        
  updated rock.simulation        
  WARN: gitorious_server_configuration is deprecated, replace by git_server_configuration
  WARN: Note that the call interface has not changed, you only need to change the method name
  updated orocos.toolchain        
                                 
  WARN: osdeps definition for rake-compiler, previously defined in .autoproj/remotes/github__orocos_toolchain_autoproj_git/orocos.osdeps overridden by autoproj/remotes/rock.core/rock.osdeps-ruby21: resp. {"gem"=>[0, ["rake-compiler<0.9.0"]]} and {"gem"=>[0, ["rake-compiler"]]}
  WARN: osdeps definition for graphviz, previously defined in .autoproj/remotes/github__orocos_toolchain_autoproj_git/orocos.osdeps overridden by autoproj/remotes/rock/rock.osdeps: resp. {"apt-dpkg"=>[0, ["graphviz"]]} and {"apt-dpkg"=>[0, ["graphviz", "graphviz-dev"]]}
autoproj: loading ...
run 'autoproj reconfigure' to change configuration options
and use 'autoproj switch-config' to change the remote source for
autoproj's main build configuration
Command finished successfully at 2015-10-21 17:52:07 +0200
goldhoorn@mgoldhoorn:~/bootstraps/all/dev$ 

```

**Comment by doudou** [comment]
Can you do an `autoproj show base/types` ?

**Comment by doudou** [comment]
and copy/paste your manifest here ?

**Comment by goldhoorn** [comment]
On 21.10.2015 18:58, Sylvain Joyeux wrote:
>
> Can you do an |autoproj show base/types| ?
>
```
goldhoorn@mgoldhoorn:~/bootstraps/all/dev$ autoproj show base/types
source package base/types
  this package is not checked out yet, the dependency information will
probably be incomplete
  source definition
  WARN: base/types from rock.core does not have a manifest
    type: git
    url: https://github.com/rock-core/base-types.git
    branch: master
    interactive: false
    push_to: git@github.com:/rock-core/base-types.git
    repository_id: github:/rock-core/base-types.git
    retry_count: 10
    first match: in rock.core
      branch: $ROCK_BRANCH
      github: rock-core/base-$PACKAGE_BASENAME
  is directly selected by the manifest via rock.core
  is ignored
  direct reverse dependencies: control/kdl, external/tinyxml,
perception/libelas
  recursive reverse dependencies: control/kdl, external/tinyxml,
perception/libelas
  directly depends on:
  optionally depends on:
  dependencies on OS packages: cmake
```

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/91#issuecomment-149961609>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by goldhoorn** [comment]
On 21.10.2015 18:59, Sylvain Joyeux wrote:
>
> and copy/paste your manifest here ?
>
unchanged version:
https://github.com/rock-core/buildconf/blob/master/manifest
(fresh bootstrap of the same buildconf)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/91#issuecomment-149961765>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
Just realized my mistake ... I'm not running autoproj build or update, only aup and amake. The latter work, I can reproduce the bug on the former.

Anyways, just pushed a fix

**Comment by goldhoorn** [comment]
:+1:  Fixed, yep
