### ISSUE TITLE
autoproj2.0: autoproj_bootsrap not recognize --no-progress 

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autoproj#94]
Following call fails:

```
+ ruby2.1 ../autoproj_bootstrap --no-progress git http://github.com/rock-core/buildconf

```

But autoproj 2.0 seems to support this option...
(replated to https://github.com/rock-core/base-build_server_scripts/pull/12)

**Comment by doudou** [comment]
Actually what I said in #92 is not true (buggy, and there are cases where autodetection fails, as e.g. if we redirect to a file).

So I'm re-adding the --no-color option to autoproj and the autoproj_bootstrap scripts

**Comment by doudou** [comment]
(and fix --no-progress obviously)

**Comment by goldhoorn** [comment]
fixed
