### ISSUE TITLE
autoproj2.0: installation of ONE autoproj setup forces other ones to use new autoproj2.0

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autoproj#95]
I played around with new bootstraps which installs autoproj in a user-wide directory. (by default)

Now all my rock installations are affected if i source any installation i get the following error afterwards:

```
goldhoorn@mgoldhoorn:~/bootstraps/gecode$ autoproj osdeps

/home/goldhoorn/bootstraps/gecode looks like a v1 workspace, run autoproj upgrade before continuing
```

```
goldhoorn@mgoldhoorn:~/bootstraps/gecode$ printenv | grep GEM
GEM_HOME=/home/goldhoorn/bootstraps/gecode/.gems
GEM_PATH=/home/goldhoorn/bootstraps/gecode/.gems:/home/goldhoorn/.gem/ruby/2.1.0:/var/lib/gems/2.1.0:/usr/share/rubygems-integration/2.1.0:/usr/share/rubygems-integration/2.1:/usr/share/rubygems-integration/all

```

**Comment by goldhoorn** [comment]
If you ran in this you have to delete the globally installed autoproj version by:
cd ~/.gems/
find -name "*autoproj*" -exec rm -fr {} \;
find -name "*autobuild*" -exec rm -fr {} \;

**Comment by doudou** [comment]
Shit ... very annoying. I assumed that the local version of autoproj (in $ROOT/.gems) would take precedence, but the highest version does :(

You can use the --private option during bootstrap to install the gems outside the common GEM_PATH. They can still be shared among autoproj 2.0 installs by providing a path, e.g.

~~~
autoproj_bootstrap --private=$HOME/.autoproj-gems
~~~

Might want to make this the default ... thoughts ?

**Comment by goldhoorn** [comment]
On 03.11.2015 13:43, Sylvain Joyeux wrote:
>
> Shit ... very annoying. I assumed that the local version of autoproj
> (in $ROOT/.gems) would take precedence, but the highest version does :(
>
> You can use the --private option during bootstrap to install the gems
> outside the common GEM_PATH. They can still be shared among autoproj
> 2.0 installs by providing a path, e.g.
>
> |autoproj_bootstrap --private=$HOME/.autoproj-gems
> |
>
> Might want to make this the default ... thoughts ?
>
+1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/95#issuecomment-153340889>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
In the meantime, one can use the 1.x version by specifying it manually on the command line

```
aup _1.13.3_ ...
autoproj _1.13.3_ build ...
```

At least not everything is lost ...

**Comment by doudou** [comment]
autoproj 2.0 now installs gems in a private folder in $HOME/.autoproj
