### ISSUE TITLE
autproj2.0: --no-osdeps is not working

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autoproj#97]
When calling ``` autoproj update --no-osdeps```

On gentoo i got:

cannot resolve libturbojpeg: it is not a package, not a metapackage and not an osdep

in between:
```  installing OS packages: dev-vcs/git```

System seems to be detected correctly:
```  operating system: gentoo -        ```

**Comment by doudou** [comment]
> cannot resolve libturbojpeg: it is not a package, not a metapackage and not an osdep

This is not a problem with --no-osdeps. Autoproj will refuse to do inconsistent things (as, referring to a package which does not exist), which is the problem here. --no-odeps will only bypass installation of osdeps.

> installing OS packages: dev-vcs/git

This one is, obviously.

**Comment by doudou** [comment]
Can you try with

```
autoproj update --osdeps=f
```

thor has an annoying but related to boolean flags :(

**Comment by goldhoorn** [comment]
On 03.11.2015 12:40, Sylvain Joyeux wrote:
>
> Can you try with
>
> |autoproj update --osdeps=f|
|Can do next time i run the VM, might take a few days...



|
> |
> |
>
> thor has an annoying but related to boolean flags :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/97#issuecomment-153327079>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by goldhoorn** [comment]
Now my env.sh is broken in the gentoo system. A reinstall with autoproj_install does not work because i get imidietly the error regarding libturbojpeg.

after i setted the PATH to the ~/.gems/bin dir i can run ```autoproj update  --osdeps=f```  but i get the same error

**Comment by doudou** [comment]
> A reinstall with autoproj_install does not work because i get imidietly the error regarding libturbojpeg.

Backtrace ? Console copy/paste ?

**Comment by doudou** [comment]
By the way, why don't you workaround the problem by .... defining the osdep ?

**Comment by goldhoorn** [comment]
Because i would like to test something really different and not using
gentoo <actively>, even my package does not depend on this lib but
autoproj yields even then...


On 05.11.2015 12:35, Sylvain Joyeux wrote:
>
> By the way, why don't you workaround the problem by .... defining the
> osdep ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/97#issuecomment-154037184>.
>


-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
A full backtrace (with --debug) would be nice, then. Autoproj should not resolve the osdep at all if it's not needed by your manifest.

**Comment by goldhoorn** [comment]
On 05.11.2015 13:10, Sylvain Joyeux wrote:
>
> A full backtrace (with --debug) would be nice
>
http://www.goldhoorn.eu/extern/autoproj_out

-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
Mmmmm ... I was wrong. Dependencies are indeed resolved globally.

I've released rc15, which has a fixed error message for this case and in which --no-osdeps should ignore the error.

In principle it would be easy to remove the check on package name resolution and push it at install time, (which would really improve the situation in your case), but I don't have the time to do that properly (i.e. with proper testing)

**Comment by goldhoorn** [comment]
On 05.11.2015 13:22, Sylvain Joyeux wrote:
>
> Mmmmm ... I was wrong. Dependencies are indeed resolved globally.
>
> I've released rc15, which has a fixed error message for this case and
> in which --no-osdeps should ignore the error.
>
> In principle it would be easy to remove the check on package name
> resolution and push it at install time, (which would really improve
> the situation in your case), but I don't have the time to do that
> properly (i.e. with proper testing)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/97#issuecomment-154044260>.
>
Would be a option to check if a os-definition for another OS exists and
then ignore this name if --no-osdeps is given?
By doing this you can identiy OS-packages as long as the have any
definition anywhere?

However, it's not urgent for me i can workaround respectively don't need
gentoo anymore (yet).

-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
> Would be a option to check if a os-definition for another OS exists and
then ignore this name if --no-osdeps is given?

This is what rc15 does.

**Comment by goldhoorn** [comment]
On 05.11.2015 13:28, Sylvain Joyeux wrote:
>
>     Would be a option to check if a os-definition for another OS
>     exists and
>     then ignore this name if --no-osdeps is given?
>
> This is what rc15 does.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rock-core/autoproj/issues/97#issuecomment-154045408>.
>

No i got another error:
update is now working,
but:

goldhoorn@localhost ~/dev/tools/constrained_based_networks $ autoproj
--no-osdeps build .
ERROR: "autoproj help" was called with arguments ["--no-osdeps",
"build", "."]
Usage: "autoproj help [COMMAND]"

btw:
goldhoorn@localhost ~/dev/tools/constrained_based_networks $ autoproj 
--version
Could not find command "__version".

Other annoying bug:
goldhoorn@localhost ~/dev/tools/constrained_based_networks $ autoproj  envsh
cannot resolve libturbojpeg: libturbojpeg is an osdep, but it is not
available for this operating system and it cannot be resolved as a
source package

goldhoorn@localhost ~/dev/tools/constrained_based_networks $ autoproj
--no-osdeps envsh
Could not find command "__no_osdeps".







-- 
 Dipl.-Inf. Matthias Goldhoorn 
 Space and Underwater Robotic

 Universität Bremen
 FB 3 - Mathematik und Informatik
 AG Robotik
 Robert-Hooke-Straße 1
 28359 Bremen, Germany
 
 Zentrale: +49 421 178 45-6611
 
 Besuchsadresse der Nebengeschäftstelle: 
 Robert-Hooke-Straße 5
 28359 Bremen, Germany
 
 Tel.:    +49 421 178 45-4193
 Empfang: +49 421 178 45-6600
 Fax:     +49 421 178 45-4150
 E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

 Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
The syntax is autoproj [GLOBAL OPTIONS] subcommand [SUBCOMMAND OPTIONS] (i.e --no-osdeps goes after build not before). I've created a PR to fix the issue with 'help', but there's a problem of maintainership on thor currently ... so basically PRs stay.
