### ISSUE TITLE
one last gem for Autoproj <2.0

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/autoproj#99]
could you please release one pre-2.0 autoprjo version which include the
--all-known-packages option.
On our buildserver we have used autoproj in master (by explicitly build
tools/autoproj).
This is not possible anymore.

This causes that we are unable to build all packages without explicitly
create a package set.

**Comment by doudou** [comment]
The commit that adds `--all-known-packages` is included in 1.13.3
